# NOGAME – Level Difficulty & Player Progression Analysis

## 1. Business Context

This analysis aims to identify puzzle levels that create excessive difficulty
or progression friction and determine which levels should be prioritized
for balancing.

The analysis focuses on three questions:

- Where are the main difficulty spikes?
- Which difficult levels are associated with higher progression drop-off?
- Which levels should be prioritized based on difficulty, player exposure,
  and progression impact?

In [63]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
data_path = ""

In [65]:
import os

files = os.listdir(data_path)
files

['ad_impression.csv',
 'winstreak_point_gained.csv',
 'earn_resource.csv',
 'spend_resource.csv',
 'winstreak_reward_claimed.csv',
 'in_app_purchase.csv',
 'level_end.csv',
 'level_start.csv',
 'buy_resource.csv']

In [66]:
import duckdb

con = duckdb.connect()

In [67]:
con.execute(f"""
SELECT *
FROM read_csv_auto('{data_path}/level_start.csv')
LIMIT 5
""").df()

,event_date,event_timestamp,user_pseudo_id,user_first_touch_timestamp,mobile_brand_name,mobile_model_name,operating_system_version,vendor_id,advertising_id,time_zone_offset_seconds,...,media_source,campaign,adset,adgroup_id,ab_test,level_id,attempt,level_index,ga_session_id,ga_session_number
0,2026-08-11,1786435230695120,e0aa291a76db2cce809da84208e472f7,1786433481577000,Samsung,SM-S928B,Android 16,\N,9824196e-6820-474c-88c1-3962cbb923a8,7200,...,\N,\N,\N,\N,"firebase_exp_abt_30:0,firebase_exp_abt_40:0,fi...",26,1,26,1786433481,1
1,2026-08-11,1786436956567443,e0aa291a76db2cce809da84208e472f7,1786433481577000,Samsung,SM-S928B,Android 16,\N,9824196e-6820-474c-88c1-3962cbb923a8,7200,...,\N,\N,\N,\N,"firebase_exp_abt_42:1,firebase_exp_abt_26:0,fi...",35,1,35,1786433481,1
2,2026-08-11,1786434283078147,e0aa291a76db2cce809da84208e472f7,1786433481577000,Samsung,SM-S928B,Android 16,\N,9824196e-6820-474c-88c1-3962cbb923a8,7200,...,\N,\N,\N,\N,"firebase_exp_abt_52:1,firebase_exp_abt_48:0,fi...",11,1,11,1786433481,1
3,2026-08-11,1786448966020772,5d4dc47a5eb5c81b4b994fba598f47c0,1786437964771000,Samsung,SM-S928B,Android 16,\N,c22509dd-6b59-49fc-906e-86bc93dcc8ff,7200,...,applovin_int,TWH010a_T5_D28_Jul04_tier1_Quang_ALV,\N,\N,"firebase_exp_abt_26:0,firebase_exp_abt_48:1,fi...",56,1,56,1786445141,2
4,2026-08-13,1786611036780966,5d4dc47a5eb5c81b4b994fba598f47c0,1786437964771000,Samsung,SM-S928B,Android 16,\N,c22509dd-6b59-49fc-906e-86bc93dcc8ff,7200,...,applovin_int,TWH010a_T5_D28_Jul04_tier1_Quang_ALV,\N,\N,"firebase_exp_abt_51:1,firebase_exp_abt_40:0,fi...",118,1,118,1786610772,10

In [68]:
con.execute(f"""
DESCRIBE
SELECT *
FROM read_csv_auto('{data_path}/level_start.csv')
""").df()

                   column_name column_type null   key default extra
0                   event_date        DATE  YES  None    None  None
1              event_timestamp      BIGINT  YES  None    None  None
2               user_pseudo_id     VARCHAR  YES  None    None  None
3   user_first_touch_timestamp      BIGINT  YES  None    None  None
4            mobile_brand_name     VARCHAR  YES  None    None  None
5            mobile_model_name     VARCHAR  YES  None    None  None
6     operating_system_version     VARCHAR  YES  None    None  None
7                    vendor_id     VARCHAR  YES  None    None  None
8               advertising_id     VARCHAR  YES  None    None  None
9     time_zone_offset_seconds      BIGINT  YES  None    None  None
10                     country     VARCHAR  YES  None    None  None
11                        city     VARCHAR  YES  None    None  None
12                 app_version     VARCHAR  YES  None    None  None
13              install_source     VARCHAR  YES  None    None  None
14         traffic_source_name     VARCHAR  YES  None    None  None
15       traffic_source_medium     VARCHAR  YES  None    None  None
16              traffic_source     VARCHAR  YES  None    None  None
17                    platform     VARCHAR  YES  None    None  None
18                appsflyer_id     VARCHAR  YES  None    None  None
19                   player_id     VARCHAR  YES  None    None  None
20                   max_level      BIGINT  YES  None    None  None
21                   iap_count      BIGINT  YES  None    None  None
22              rewarded_count      BIGINT  YES  None    None  None
23                 inter_count      BIGINT  YES  None    None  None
24                coin_balance      BIGINT  YES  None    None  None
25                  coin_total      BIGINT  YES  None    None  None
26                        life     VARCHAR  YES  None    None  None
27                   af_status     VARCHAR  YES  None    None  None
28                media_source     VARCHAR  YES  None    None  None
29                    campaign     VARCHAR  YES  None    None  None
30                       adset     VARCHAR  YES  None    None  None
31                  adgroup_id     VARCHAR  YES  None    None  None
32                     ab_test     VARCHAR  YES  None    None  None
33                    level_id      BIGINT  YES  None    None  None
34                     attempt      BIGINT  YES  None    None  None
35                 level_index      BIGINT  YES  None    None  None
36               ga_session_id      BIGINT  YES  None    None  None
37           ga_session_number      BIGINT  YES  None    None  None

In [69]:
import os

csv_files = [f for f in os.listdir(data_path) if f.endswith(".csv")]

for f in csv_files:
    print("\n" + "="*80)
    print(f)

    try:
        schema = con.execute(f"""
        DESCRIBE
        SELECT *
        FROM read_csv_auto('{data_path}/{f}')
        """).df()

        display(schema)

    except Exception as e:
        print("ERROR:", e)

================================================================================
ad_impression.csv

                   column_name column_type null   key default extra
0                   event_date        DATE  YES  None    None  None
1              event_timestamp      BIGINT  YES  None    None  None
2               user_pseudo_id     VARCHAR  YES  None    None  None
3   user_first_touch_timestamp      BIGINT  YES  None    None  None
4            mobile_brand_name     VARCHAR  YES  None    None  None
5            mobile_model_name     VARCHAR  YES  None    None  None
6     operating_system_version     VARCHAR  YES  None    None  None
7                    vendor_id     VARCHAR  YES  None    None  None
8               advertising_id     VARCHAR  YES  None    None  None
9     time_zone_offset_seconds      BIGINT  YES  None    None  None
10                     country     VARCHAR  YES  None    None  None
11                        city     VARCHAR  YES  None    None  None
12                 app_version     VARCHAR  YES  None    None  None
13              install_source     VARCHAR  YES  None    None  None
14         traffic_source_name     VARCHAR  YES  None    None  None
15       traffic_source_medium     VARCHAR  YES  None    None  None
16              traffic_source     VARCHAR  YES  None    None  None
17                    platform     VARCHAR  YES  None    None  None
18                appsflyer_id     VARCHAR  YES  None    None  None
19                   player_id     VARCHAR  YES  None    None  None
20                   max_level      BIGINT  YES  None    None  None
21                   iap_count      BIGINT  YES  None    None  None
22              rewarded_count      BIGINT  YES  None    None  None
23                 inter_count      BIGINT  YES  None    None  None
24                coin_balance      BIGINT  YES  None    None  None
25                  coin_total      BIGINT  YES  None    None  None
26                        life     VARCHAR  YES  None    None  None
27                   af_status     VARCHAR  YES  None    None  None
28                media_source     VARCHAR  YES  None    None  None
29                    campaign     VARCHAR  YES  None    None  None
30                       adset     VARCHAR  YES  None    None  None
31                  adgroup_id     VARCHAR  YES  None    None  None
32                     ab_test     VARCHAR  YES  None    None  None
33                 ad_platform     VARCHAR  YES  None    None  None
34                   ad_source     VARCHAR  YES  None    None  None
35                   ad_format     VARCHAR  YES  None    None  None
36                ad_unit_name     VARCHAR  YES  None    None  None
37                   placement     VARCHAR  YES  None    None  None
38                    currency     VARCHAR  YES  None    None  None
39                       value      DOUBLE  YES  None    None  None
40               ga_session_id      BIGINT  YES  None    None  None
41           ga_session_number      BIGINT  YES  None    None  None

================================================================================
winstreak_point_gained.csv

                   column_name column_type null   key default extra
0                   event_date        DATE  YES  None    None  None
1              event_timestamp      BIGINT  YES  None    None  None
2               user_pseudo_id     VARCHAR  YES  None    None  None
3   user_first_touch_timestamp      BIGINT  YES  None    None  None
4            mobile_brand_name     VARCHAR  YES  None    None  None
5            mobile_model_name     VARCHAR  YES  None    None  None
6     operating_system_version     VARCHAR  YES  None    None  None
7                    vendor_id     VARCHAR  YES  None    None  None
8               advertising_id     VARCHAR  YES  None    None  None
9     time_zone_offset_seconds      BIGINT  YES  None    None  None
10                     country     VARCHAR  YES  None    None  None
11                        city     VARCHAR  YES  None    None  None
12                 app_version     VARCHAR  YES  None    None  None
13              install_source     VARCHAR  YES  None    None  None
14         traffic_source_name     VARCHAR  YES  None    None  None
15       traffic_source_medium     VARCHAR  YES  None    None  None
16              traffic_source     VARCHAR  YES  None    None  None
17                    platform     VARCHAR  YES  None    None  None
18                appsflyer_id     VARCHAR  YES  None    None  None
19                   player_id     VARCHAR  YES  None    None  None
20                   max_level      BIGINT  YES  None    None  None
21                   iap_count      BIGINT  YES  None    None  None
22              rewarded_count      BIGINT  YES  None    None  None
23                 inter_count      BIGINT  YES  None    None  None
24                coin_balance      BIGINT  YES  None    None  None
25                  coin_total      BIGINT  YES  None    None  None
26                        life     VARCHAR  YES  None    None  None
27                   af_status     VARCHAR  YES  None    None  None
28                media_source     VARCHAR  YES  None    None  None
29                    campaign     VARCHAR  YES  None    None  None
30                       adset     VARCHAR  YES  None    None  None
31                  adgroup_id     VARCHAR  YES  None    None  None
32                     ab_test     VARCHAR  YES  None    None  None
33              current_streak      BIGINT  YES  None    None  None
34               points_gained      BIGINT  YES  None    None  None
35        current_total_points      BIGINT  YES  None    None  None
36                    level_id     VARCHAR  YES  None    None  None
37               ga_session_id      BIGINT  YES  None    None  None
38           ga_session_number      BIGINT  YES  None    None  None

================================================================================
earn_resource.csv

                   column_name column_type null   key default extra
0                   event_date        DATE  YES  None    None  None
1              event_timestamp      BIGINT  YES  None    None  None
2               user_pseudo_id     VARCHAR  YES  None    None  None
3   user_first_touch_timestamp      BIGINT  YES  None    None  None
4            mobile_brand_name     VARCHAR  YES  None    None  None
5            mobile_model_name     VARCHAR  YES  None    None  None
6     operating_system_version     VARCHAR  YES  None    None  None
7                    vendor_id     VARCHAR  YES  None    None  None
8               advertising_id     VARCHAR  YES  None    None  None
9     time_zone_offset_seconds      BIGINT  YES  None    None  None
10                     country     VARCHAR  YES  None    None  None
11                        city     VARCHAR  YES  None    None  None
12                 app_version     VARCHAR  YES  None    None  None
13              install_source     VARCHAR  YES  None    None  None
14         traffic_source_name     VARCHAR  YES  None    None  None
15       traffic_source_medium     VARCHAR  YES  None    None  None
16              traffic_source     VARCHAR  YES  None    None  None
17                    platform     VARCHAR  YES  None    None  None
18                appsflyer_id     VARCHAR  YES  None    None  None
19                   player_id     VARCHAR  YES  None    None  None
20                   max_level      BIGINT  YES  None    None  None
21                   iap_count      BIGINT  YES  None    None  None
22              rewarded_count      BIGINT  YES  None    None  None
23                 inter_count      BIGINT  YES  None    None  None
24                coin_balance      BIGINT  YES  None    None  None
25                  coin_total      BIGINT  YES  None    None  None
26                        life     VARCHAR  YES  None    None  None
27                   af_status     VARCHAR  YES  None    None  None
28                media_source     VARCHAR  YES  None    None  None
29                    campaign     VARCHAR  YES  None    None  None
30                       adset     VARCHAR  YES  None    None  None
31                  adgroup_id     VARCHAR  YES  None    None  None
32                     ab_test     VARCHAR  YES  None    None  None
33               item_category     VARCHAR  YES  None    None  None
34                     item_id     VARCHAR  YES  None    None  None
35                      source     VARCHAR  YES  None    None  None
36                   source_id     VARCHAR  YES  None    None  None
37                       value      BIGINT  YES  None    None  None
38               value_balance      BIGINT  YES  None    None  None
39               ga_session_id     VARCHAR  YES  None    None  None
40           ga_session_number     VARCHAR  YES  None    None  None

================================================================================
spend_resource.csv

                   column_name column_type null   key default extra
0                   event_date        DATE  YES  None    None  None
1              event_timestamp      BIGINT  YES  None    None  None
2               user_pseudo_id     VARCHAR  YES  None    None  None
3   user_first_touch_timestamp      BIGINT  YES  None    None  None
4            mobile_brand_name     VARCHAR  YES  None    None  None
5            mobile_model_name     VARCHAR  YES  None    None  None
6     operating_system_version     VARCHAR  YES  None    None  None
7                    vendor_id     VARCHAR  YES  None    None  None
8               advertising_id     VARCHAR  YES  None    None  None
9     time_zone_offset_seconds      BIGINT  YES  None    None  None
10                     country     VARCHAR  YES  None    None  None
11                        city     VARCHAR  YES  None    None  None
12                 app_version     VARCHAR  YES  None    None  None
13              install_source     VARCHAR  YES  None    None  None
14         traffic_source_name     VARCHAR  YES  None    None  None
15       traffic_source_medium     VARCHAR  YES  None    None  None
16              traffic_source     VARCHAR  YES  None    None  None
17                    platform     VARCHAR  YES  None    None  None
18                appsflyer_id     VARCHAR  YES  None    None  None
19                   player_id     VARCHAR  YES  None    None  None
20                   max_level      BIGINT  YES  None    None  None
21                   iap_count      BIGINT  YES  None    None  None
22              rewarded_count      BIGINT  YES  None    None  None
23                 inter_count      BIGINT  YES  None    None  None
24                coin_balance      BIGINT  YES  None    None  None
25                  coin_total      BIGINT  YES  None    None  None
26                        life     VARCHAR  YES  None    None  None
27                   af_status     VARCHAR  YES  None    None  None
28                media_source     VARCHAR  YES  None    None  None
29                    campaign     VARCHAR  YES  None    None  None
30                       adset     VARCHAR  YES  None    None  None
31                  adgroup_id     VARCHAR  YES  None    None  None
32                     ab_test     VARCHAR  YES  None    None  None
33               item_category     VARCHAR  YES  None    None  None
34                     item_id     VARCHAR  YES  None    None  None
35                      source     VARCHAR  YES  None    None  None
36                   source_id     VARCHAR  YES  None    None  None
37                       value      BIGINT  YES  None    None  None
38               value_balance      BIGINT  YES  None    None  None
39               ga_session_id      BIGINT  YES  None    None  None
40           ga_session_number      BIGINT  YES  None    None  None

================================================================================
winstreak_reward_claimed.csv

                   column_name column_type null   key default extra
0                   event_date        DATE  YES  None    None  None
1              event_timestamp      BIGINT  YES  None    None  None
2               user_pseudo_id     VARCHAR  YES  None    None  None
3   user_first_touch_timestamp      BIGINT  YES  None    None  None
4            mobile_brand_name     VARCHAR  YES  None    None  None
5            mobile_model_name     VARCHAR  YES  None    None  None
6     operating_system_version     VARCHAR  YES  None    None  None
7                    vendor_id     VARCHAR  YES  None    None  None
8               advertising_id     VARCHAR  YES  None    None  None
9     time_zone_offset_seconds      BIGINT  YES  None    None  None
10                     country     VARCHAR  YES  None    None  None
11                        city     VARCHAR  YES  None    None  None
12                 app_version     VARCHAR  YES  None    None  None
13              install_source     VARCHAR  YES  None    None  None
14         traffic_source_name     VARCHAR  YES  None    None  None
15       traffic_source_medium     VARCHAR  YES  None    None  None
16              traffic_source     VARCHAR  YES  None    None  None
17                    platform     VARCHAR  YES  None    None  None
18                appsflyer_id     VARCHAR  YES  None    None  None
19                   player_id     VARCHAR  YES  None    None  None
20                   max_level      BIGINT  YES  None    None  None
21                   iap_count      BIGINT  YES  None    None  None
22              rewarded_count      BIGINT  YES  None    None  None
23                 inter_count      BIGINT  YES  None    None  None
24                coin_balance      BIGINT  YES  None    None  None
25                  coin_total      BIGINT  YES  None    None  None
26                        life     VARCHAR  YES  None    None  None
27                   af_status     VARCHAR  YES  None    None  None
28                media_source     VARCHAR  YES  None    None  None
29                    campaign     VARCHAR  YES  None    None  None
30                       adset     VARCHAR  YES  None    None  None
31                  adgroup_id     VARCHAR  YES  None    None  None
32                     ab_test     VARCHAR  YES  None    None  None
33                milestone_id      BIGINT  YES  None    None  None
34         event_instance_date     VARCHAR  YES  None    None  None
35               ga_session_id     VARCHAR  YES  None    None  None
36           ga_session_number     VARCHAR  YES  None    None  None

================================================================================
in_app_purchase.csv

                   column_name column_type null   key default extra
0                   event_date        DATE  YES  None    None  None
1              event_timestamp      BIGINT  YES  None    None  None
2               user_pseudo_id     VARCHAR  YES  None    None  None
3   user_first_touch_timestamp      BIGINT  YES  None    None  None
4            mobile_brand_name     VARCHAR  YES  None    None  None
5            mobile_model_name     VARCHAR  YES  None    None  None
6     operating_system_version     VARCHAR  YES  None    None  None
7                    vendor_id     VARCHAR  YES  None    None  None
8               advertising_id     VARCHAR  YES  None    None  None
9     time_zone_offset_seconds      BIGINT  YES  None    None  None
10                     country     VARCHAR  YES  None    None  None
11                        city     VARCHAR  YES  None    None  None
12                 app_version     VARCHAR  YES  None    None  None
13              install_source     VARCHAR  YES  None    None  None
14         traffic_source_name     VARCHAR  YES  None    None  None
15       traffic_source_medium     VARCHAR  YES  None    None  None
16              traffic_source     VARCHAR  YES  None    None  None
17                    platform     VARCHAR  YES  None    None  None
18                appsflyer_id     VARCHAR  YES  None    None  None
19                   player_id     VARCHAR  YES  None    None  None
20                   max_level      BIGINT  YES  None    None  None
21                   iap_count      BIGINT  YES  None    None  None
22              rewarded_count      BIGINT  YES  None    None  None
23                 inter_count      BIGINT  YES  None    None  None
24                coin_balance      BIGINT  YES  None    None  None
25                  coin_total      BIGINT  YES  None    None  None
26                        life     VARCHAR  YES  None    None  None
27                   af_status     VARCHAR  YES  None    None  None
28                media_source     VARCHAR  YES  None    None  None
29                    campaign     VARCHAR  YES  None    None  None
30                       adset     VARCHAR  YES  None    None  None
31                  adgroup_id     VARCHAR  YES  None    None  None
32                     ab_test     VARCHAR  YES  None    None  None
33                  product_id     VARCHAR  YES  None    None  None
34          event_value_in_usd      DOUBLE  YES  None    None  None
35               ga_session_id      BIGINT  YES  None    None  None
36           ga_session_number      BIGINT  YES  None    None  None

================================================================================
level_end.csv

                   column_name column_type null   key default extra
0                   event_date        DATE  YES  None    None  None
1              event_timestamp      BIGINT  YES  None    None  None
2               user_pseudo_id     VARCHAR  YES  None    None  None
3   user_first_touch_timestamp      BIGINT  YES  None    None  None
4            mobile_brand_name     VARCHAR  YES  None    None  None
5            mobile_model_name     VARCHAR  YES  None    None  None
6     operating_system_version     VARCHAR  YES  None    None  None
7                    vendor_id     VARCHAR  YES  None    None  None
8               advertising_id     VARCHAR  YES  None    None  None
9     time_zone_offset_seconds      BIGINT  YES  None    None  None
10                     country     VARCHAR  YES  None    None  None
11                        city     VARCHAR  YES  None    None  None
12                 app_version     VARCHAR  YES  None    None  None
13              install_source     VARCHAR  YES  None    None  None
14         traffic_source_name     VARCHAR  YES  None    None  None
15       traffic_source_medium     VARCHAR  YES  None    None  None
16              traffic_source     VARCHAR  YES  None    None  None
17                    platform     VARCHAR  YES  None    None  None
18                appsflyer_id     VARCHAR  YES  None    None  None
19                   player_id     VARCHAR  YES  None    None  None
20                   max_level      BIGINT  YES  None    None  None
21                   iap_count      BIGINT  YES  None    None  None
22              rewarded_count      BIGINT  YES  None    None  None
23                 inter_count      BIGINT  YES  None    None  None
24                coin_balance      BIGINT  YES  None    None  None
25                  coin_total      BIGINT  YES  None    None  None
26                        life     VARCHAR  YES  None    None  None
27                   af_status     VARCHAR  YES  None    None  None
28                media_source     VARCHAR  YES  None    None  None
29                    campaign     VARCHAR  YES  None    None  None
30                       adset     VARCHAR  YES  None    None  None
31                  adgroup_id     VARCHAR  YES  None    None  None
32                     ab_test     VARCHAR  YES  None    None  None
33                    level_id      BIGINT  YES  None    None  None
34                 level_index      BIGINT  YES  None    None  None
35                     attempt      BIGINT  YES  None    None  None
36                      status      BIGINT  YES  None    None  None
37                    playtime      BIGINT  YES  None    None  None
38                      revive      BIGINT  YES  None    None  None
39                   booster_0     VARCHAR  YES  None    None  None
40                   booster_1     VARCHAR  YES  None    None  None
41                   booster_2     VARCHAR  YES  None    None  None
42                   booster_3     VARCHAR  YES  None    None  None
43              unsolved_items      BIGINT  YES  None    None  None
44                 total_items      BIGINT  YES  None    None  None
45                        move      BIGINT  YES  None    None  None
46               ga_session_id      BIGINT  YES  None    None  None
47           ga_session_number      BIGINT  YES  None    None  None

================================================================================
level_start.csv

                   column_name column_type null   key default extra
0                   event_date        DATE  YES  None    None  None
1              event_timestamp      BIGINT  YES  None    None  None
2               user_pseudo_id     VARCHAR  YES  None    None  None
3   user_first_touch_timestamp      BIGINT  YES  None    None  None
4            mobile_brand_name     VARCHAR  YES  None    None  None
5            mobile_model_name     VARCHAR  YES  None    None  None
6     operating_system_version     VARCHAR  YES  None    None  None
7                    vendor_id     VARCHAR  YES  None    None  None
8               advertising_id     VARCHAR  YES  None    None  None
9     time_zone_offset_seconds      BIGINT  YES  None    None  None
10                     country     VARCHAR  YES  None    None  None
11                        city     VARCHAR  YES  None    None  None
12                 app_version     VARCHAR  YES  None    None  None
13              install_source     VARCHAR  YES  None    None  None
14         traffic_source_name     VARCHAR  YES  None    None  None
15       traffic_source_medium     VARCHAR  YES  None    None  None
16              traffic_source     VARCHAR  YES  None    None  None
17                    platform     VARCHAR  YES  None    None  None
18                appsflyer_id     VARCHAR  YES  None    None  None
19                   player_id     VARCHAR  YES  None    None  None
20                   max_level      BIGINT  YES  None    None  None
21                   iap_count      BIGINT  YES  None    None  None
22              rewarded_count      BIGINT  YES  None    None  None
23                 inter_count      BIGINT  YES  None    None  None
24                coin_balance      BIGINT  YES  None    None  None
25                  coin_total      BIGINT  YES  None    None  None
26                        life     VARCHAR  YES  None    None  None
27                   af_status     VARCHAR  YES  None    None  None
28                media_source     VARCHAR  YES  None    None  None
29                    campaign     VARCHAR  YES  None    None  None
30                       adset     VARCHAR  YES  None    None  None
31                  adgroup_id     VARCHAR  YES  None    None  None
32                     ab_test     VARCHAR  YES  None    None  None
33                    level_id      BIGINT  YES  None    None  None
34                     attempt      BIGINT  YES  None    None  None
35                 level_index      BIGINT  YES  None    None  None
36               ga_session_id      BIGINT  YES  None    None  None
37           ga_session_number      BIGINT  YES  None    None  None

================================================================================
buy_resource.csv

                   column_name column_type null   key default extra
0                   event_date        DATE  YES  None    None  None
1              event_timestamp      BIGINT  YES  None    None  None
2               user_pseudo_id     VARCHAR  YES  None    None  None
3   user_first_touch_timestamp      BIGINT  YES  None    None  None
4            mobile_brand_name     VARCHAR  YES  None    None  None
5            mobile_model_name     VARCHAR  YES  None    None  None
6     operating_system_version     VARCHAR  YES  None    None  None
7                    vendor_id     VARCHAR  YES  None    None  None
8               advertising_id     VARCHAR  YES  None    None  None
9     time_zone_offset_seconds      BIGINT  YES  None    None  None
10                     country     VARCHAR  YES  None    None  None
11                        city     VARCHAR  YES  None    None  None
12                 app_version     VARCHAR  YES  None    None  None
13              install_source     VARCHAR  YES  None    None  None
14         traffic_source_name     VARCHAR  YES  None    None  None
15       traffic_source_medium     VARCHAR  YES  None    None  None
16              traffic_source     VARCHAR  YES  None    None  None
17                    platform     VARCHAR  YES  None    None  None
18                appsflyer_id     VARCHAR  YES  None    None  None
19                   player_id     VARCHAR  YES  None    None  None
20                   max_level      BIGINT  YES  None    None  None
21                   iap_count      BIGINT  YES  None    None  None
22              rewarded_count      BIGINT  YES  None    None  None
23                 inter_count      BIGINT  YES  None    None  None
24                coin_balance      BIGINT  YES  None    None  None
25                  coin_total      BIGINT  YES  None    None  None
26                        life     VARCHAR  YES  None    None  None
27                   af_status     VARCHAR  YES  None    None  None
28                media_source     VARCHAR  YES  None    None  None
29                    campaign     VARCHAR  YES  None    None  None
30                       adset     VARCHAR  YES  None    None  None
31                  adgroup_id     VARCHAR  YES  None    None  None
32                     ab_test     VARCHAR  YES  None    None  None
33               item_category     VARCHAR  YES  None    None  None
34                     item_id     VARCHAR  YES  None    None  None
35                      source     VARCHAR  YES  None    None  None
36               source_detail     VARCHAR  YES  None    None  None
37                   source_id     VARCHAR  YES  None    None  None
38                       value      BIGINT  YES  None    None  None
39               value_balance      BIGINT  YES  None    None  None
40               ga_session_id      BIGINT  YES  None    None  None
41           ga_session_number      BIGINT  YES  None    None  None

In [70]:
row_counts = []

for f in csv_files:
    try:
        n = con.execute(f"""
        SELECT COUNT(*)
        FROM read_csv_auto('{data_path}/{f}')
        """).fetchone()[0]

        row_counts.append({
            "file": f,
            "rows": n
        })

    except Exception as e:
        row_counts.append({
            "file": f,
            "rows": None
        })

import pandas as pd

row_counts_df = pd.DataFrame(row_counts)
row_counts_df

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

                           file     rows
0             ad_impression.csv   534807
1    winstreak_point_gained.csv   465523
2             earn_resource.csv  1039086
3            spend_resource.csv   172813
4  winstreak_reward_claimed.csv    46754
5           in_app_purchase.csv     1319
6                 level_end.csv  1213909
7               level_start.csv  1287663
8              buy_resource.csv     7979

In [71]:
for f in csv_files:
    print("\n" + "="*80)
    print(f)

    sample = con.execute(f"""
    SELECT *
    FROM read_csv_auto('{data_path}/{f}')
    LIMIT 5
    """).df()

    display(sample)

================================================================================
ad_impression.csv

,event_date,event_timestamp,user_pseudo_id,user_first_touch_timestamp,mobile_brand_name,mobile_model_name,operating_system_version,vendor_id,advertising_id,time_zone_offset_seconds,...,ab_test,ad_platform,ad_source,ad_format,ad_unit_name,placement,currency,value,ga_session_id,ga_session_number
0,2026-08-10,1786412519370002,4928DB91F3AC42EE80B600A13AC6E698,1786235166674000,Apple,iPhone 13,iOS 26.6,B294A5AA-A377-4A61-AE78-DC04BA8EBE3E,None,-18000,...,"firebase_exp_abt_31:0,firebase_exp_abt_49:0,fi...",appLovin,Unity Ads,INTER,9f4bad1d4345650b,win_inter,USD,0.045402,1786408280,3
1,2026-08-09,1786325961443648,4928DB91F3AC42EE80B600A13AC6E698,1786235166674000,Apple,iPhone 13,iOS 26.6,B294A5AA-A377-4A61-AE78-DC04BA8EBE3E,None,-18000,...,"firebase_exp_abt_41:1,firebase_exp_abt_31:0,fi...",appLovin,Liftoff Monetize,INTER,9f4bad1d4345650b,win_inter,USD,0.016975,1786319788,2
2,2026-08-09,1786324627538742,4928DB91F3AC42EE80B600A13AC6E698,1786235166674000,Apple,iPhone 13,iOS 26.6,B294A5AA-A377-4A61-AE78-DC04BA8EBE3E,None,-18000,...,"firebase_exp_abt_53:1,firebase_exp_abt_43:0,fi...",appLovin,AppLovin,INTER,9f4bad1d4345650b,win_inter,USD,0.032097,1786319788,2
3,2026-08-09,1786324909032742,4928DB91F3AC42EE80B600A13AC6E698,1786235166674000,Apple,iPhone 13,iOS 26.6,B294A5AA-A377-4A61-AE78-DC04BA8EBE3E,None,-18000,...,"firebase_exp_abt_53:1,firebase_exp_abt_43:0,fi...",appLovin,AppLovin,INTER,9f4bad1d4345650b,win_inter,USD,0.019514,1786319788,2
4,2026-08-10,1786409818695325,4928DB91F3AC42EE80B600A13AC6E698,1786235166674000,Apple,iPhone 13,iOS 26.6,B294A5AA-A377-4A61-AE78-DC04BA8EBE3E,None,-18000,...,"firebase_exp_abt_31:0,firebase_exp_abt_43:0,fi...",appLovin,Unity Ads,INTER,9f4bad1d4345650b,win_inter,USD,0.056032,1786408280,3

================================================================================
winstreak_point_gained.csv

,event_date,event_timestamp,user_pseudo_id,user_first_touch_timestamp,mobile_brand_name,mobile_model_name,operating_system_version,vendor_id,advertising_id,time_zone_offset_seconds,...,campaign,adset,adgroup_id,ab_test,current_streak,points_gained,current_total_points,level_id,ga_session_id,ga_session_number
0,2026-08-05,1785934853069526,eaea72e08cb16600b83da9068521a2fb,1785812083839000,Samsung,SM-S901B,Android 16,\N,5297adfb-75cb-4ca7-921b-0daaf1295b08,7200,...,TWH010a_T5_D28_Jul04_tier1_Quang_ALV,\N,\N,"firebase_exp_abt_26:1,firebase_exp_abt_30:0,fi...",1,1,1566,\N,1785932304,4
1,2026-08-06,1786030925503382,eaea72e08cb16600b83da9068521a2fb,1785812083839000,Samsung,SM-S901B,Android 16,\N,5297adfb-75cb-4ca7-921b-0daaf1295b08,7200,...,TWH010a_T5_D28_Jul04_tier1_Quang_ALV,\N,\N,"firebase_exp_abt_40:0,firebase_exp_abt_42:0,fi...",8,100,5073,\N,1786029667,7
2,2026-08-05,1785934956196526,eaea72e08cb16600b83da9068521a2fb,1785812083839000,Samsung,SM-S901B,Android 16,\N,5297adfb-75cb-4ca7-921b-0daaf1295b08,7200,...,TWH010a_T5_D28_Jul04_tier1_Quang_ALV,\N,\N,"firebase_exp_abt_26:1,firebase_exp_abt_30:0,fi...",2,5,1571,\N,1785932304,4
3,2026-08-05,1785939976942170,eaea72e08cb16600b83da9068521a2fb,1785812083839000,Samsung,SM-S901B,Android 16,\N,5297adfb-75cb-4ca7-921b-0daaf1295b08,7200,...,TWH010a_T5_D28_Jul04_tier1_Quang_ALV,\N,\N,"firebase_exp_abt_34:1,firebase_exp_abt_26:1,fi...",6,100,2871,\N,1785932304,4
4,2026-08-06,1786014925189141,eaea72e08cb16600b83da9068521a2fb,1785812083839000,Samsung,SM-S901B,Android 16,\N,5297adfb-75cb-4ca7-921b-0daaf1295b08,7200,...,TWH010a_T5_D28_Jul04_tier1_Quang_ALV,\N,\N,"firebase_exp_abt_30:0,firebase_exp_abt_48:0,fi...",1,1,3219,\N,1786014048,6

================================================================================
earn_resource.csv

,event_date,event_timestamp,user_pseudo_id,user_first_touch_timestamp,mobile_brand_name,mobile_model_name,operating_system_version,vendor_id,advertising_id,time_zone_offset_seconds,...,adgroup_id,ab_test,item_category,item_id,source,source_id,value,value_balance,ga_session_id,ga_session_number
0,2026-08-02,1785681015880722,E255D8C357C84D7DA09D21E7458A2A7A,1785430718087000,Apple,iPhone 13 mini,iOS 26.5.2,583AAF80-D557-4FBB-BF9F-51092AA77CD5,None,7200,...,\N,"firebase_exp_abt_29:0,firebase_exp_abt_33:1,fi...",\N,\N,ads_x2,131_131,80,1330,1785680471,16
1,2026-08-03,1785777726193874,E255D8C357C84D7DA09D21E7458A2A7A,1785430718087000,Apple,iPhone 13 mini,iOS 26.5.2,583AAF80-D557-4FBB-BF9F-51092AA77CD5,None,7200,...,\N,"firebase_exp_abt_35:0,firebase_exp_abt_11:0,fi...",\N,\N,ads_x2,208_208,80,500,1785775663,23
2,2026-08-03,1785779966005108,E255D8C357C84D7DA09D21E7458A2A7A,1785430718087000,Apple,iPhone 13 mini,iOS 26.5.2,583AAF80-D557-4FBB-BF9F-51092AA77CD5,None,7200,...,\N,"firebase_exp_abt_11:0,firebase_exp_abt_31:0,fi...",\N,\N,ads_x2,212_212,80,980,1785775663,23
3,2026-08-02,1785668949829072,E255D8C357C84D7DA09D21E7458A2A7A,1785430718087000,Apple,iPhone 13 mini,iOS 26.5.2,583AAF80-D557-4FBB-BF9F-51092AA77CD5,None,7200,...,\N,"firebase_exp_abt_27:1,firebase_exp_abt_35:0,fi...",\N,\N,ads_x2,123_123,80,370,1785663159,12
4,2026-08-02,1785666135984190,E255D8C357C84D7DA09D21E7458A2A7A,1785430718087000,Apple,iPhone 13 mini,iOS 26.5.2,583AAF80-D557-4FBB-BF9F-51092AA77CD5,None,7200,...,\N,"firebase_exp_abt_21:1,firebase_exp_abt_11:0,fi...",\N,\N,ads_x2,113_113,80,770,1785663159,12

================================================================================
spend_resource.csv

,event_date,event_timestamp,user_pseudo_id,user_first_touch_timestamp,mobile_brand_name,mobile_model_name,operating_system_version,vendor_id,advertising_id,time_zone_offset_seconds,...,adgroup_id,ab_test,item_category,item_id,source,source_id,value,value_balance,ga_session_id,ga_session_number
0,2026-08-04,1785897191191980,544b79fc17668fd6623c451da5768538,1783395488971000,\N,\N,Android 12,\N,d2c2b64c-1281-4afa-9b4a-a3c24f3f19d5,-14400,...,\N,"firebase_exp_abt_28:1,firebase_exp_abt_22:0,fi...",\N,\N,level_play,24_24,1,0,1785896876,4
1,2026-08-04,1785897126440784,544b79fc17668fd6623c451da5768538,1783395488971000,\N,\N,Android 12,\N,d2c2b64c-1281-4afa-9b4a-a3c24f3f19d5,-14400,...,\N,"firebase_exp_abt_24:1,firebase_exp_abt_22:0,fi...",\N,\N,revive,23_23,900,260,1785896876,4
2,2026-08-12,1786549866154360,10b5d8729f2f84ad58aca32827fa2592,1783701074859000,\N,\N,Android 14,\N,fb75da3d-997a-4430-ab62-305309a41258,7200,...,\N,"firebase_exp_abt_40:1,firebase_exp_abt_51:0,fi...",\N,\N,level_play,321_321,1,0,1786546845,72
3,2026-08-11,1786447185993912,10b5d8729f2f84ad58aca32827fa2592,1783701074859000,\N,\N,Android 14,\N,fb75da3d-997a-4430-ab62-305309a41258,7200,...,\N,"firebase_exp_abt_26:0,firebase_exp_abt_40:1,fi...",\N,\N,level_play,306_306,1,0,1786446351,69
4,2026-08-12,1786547501622108,10b5d8729f2f84ad58aca32827fa2592,1783701074859000,\N,\N,Android 14,\N,fb75da3d-997a-4430-ab62-305309a41258,7200,...,\N,"firebase_exp_abt_51:0,firebase_exp_abt_40:1,fi...",\N,\N,level_play,317_317,1,0,1786546845,72

================================================================================
winstreak_reward_claimed.csv

,event_date,event_timestamp,user_pseudo_id,user_first_touch_timestamp,mobile_brand_name,mobile_model_name,operating_system_version,vendor_id,advertising_id,time_zone_offset_seconds,...,af_status,media_source,campaign,adset,adgroup_id,ab_test,milestone_id,event_instance_date,ga_session_id,ga_session_number
0,2026-08-04,1785897165534980,544b79fc17668fd6623c451da5768538,1783395488971000,\N,\N,Android 12,\N,d2c2b64c-1281-4afa-9b4a-a3c24f3f19d5,-14400,...,Non-organic,applovin_int,\N,\N,\N,"firebase_exp_abt_22:0,firebase_exp_abt_24:1,fi...",1,\N,1785896876,4
1,2026-08-12,1786548003996287,10b5d8729f2f84ad58aca32827fa2592,1783701074859000,\N,\N,Android 14,\N,fb75da3d-997a-4430-ab62-305309a41258,7200,...,Organic,\N,\N,\N,\N,"firebase_exp_abt_26:0,firebase_exp_abt_42:0,fi...",2,\N,1786546845,72
2,2026-08-11,1786466332844272,10b5d8729f2f84ad58aca32827fa2592,1783701074859000,\N,\N,Android 14,\N,fb75da3d-997a-4430-ab62-305309a41258,7200,...,Organic,\N,\N,\N,\N,"firebase_exp_abt_52:0,firebase_exp_abt_26:0,fi...",1,\N,1786465761,70
3,2026-08-10,1786381876300502,69a31b29385e31fb7a1ede8f17bf7c0d,1783748752650000,\N,\N,Android 15,\N,a01d53bd-c061-4d6a-bfc8-a98483c146d3,7200,...,Non-organic,applovin_int,\N,\N,\N,"firebase_exp_abt_48:0,firebase_exp_abt_52:0,fi...",2,\N,1786379110,42
4,2026-08-07,1786132607394455,69a31b29385e31fb7a1ede8f17bf7c0d,1783748752650000,\N,\N,Android 15,\N,a01d53bd-c061-4d6a-bfc8-a98483c146d3,7200,...,Non-organic,applovin_int,\N,\N,\N,"firebase_exp_abt_48:0,firebase_exp_abt_30:1,fi...",3,\N,1786131872,40

================================================================================
in_app_purchase.csv

,event_date,event_timestamp,user_pseudo_id,user_first_touch_timestamp,mobile_brand_name,mobile_model_name,operating_system_version,vendor_id,advertising_id,time_zone_offset_seconds,...,af_status,media_source,campaign,adset,adgroup_id,ab_test,product_id,event_value_in_usd,ga_session_id,ga_session_number
0,2026-08-04,1785902856988887,8c5830ca411ff94bfd6488f6a5a8ae32,1782961079809000,Samsung,SM-F741U,Android 16,\N,45852b96-4381-417a-a356-be7daea32a47,-25200,...,Non-organic,applovin_int,\N,\N,\N,"firebase_exp_abt_28:1,firebase_exp_abt_20:1,fi...",com.twh010.farm.sort.small_pack,9.99,1785898669,38
1,2026-08-06,1786042678776702,8c5830ca411ff94bfd6488f6a5a8ae32,1782961079809000,Samsung,SM-F741U,Android 16,\N,45852b96-4381-417a-a356-be7daea32a47,-25200,...,Non-organic,applovin_int,\N,\N,\N,"firebase_exp_abt_48:0,firebase_exp_abt_46:1,fi...",com.twh010.farm.sort.small_pack,9.99,1786033241,40
2,2026-08-06,1786037043136201,8c5830ca411ff94bfd6488f6a5a8ae32,1782961079809000,Samsung,SM-F741U,Android 16,\N,45852b96-4381-417a-a356-be7daea32a47,-25200,...,Non-organic,applovin_int,\N,\N,\N,"firebase_exp_abt_26:0,firebase_exp_abt_42:1,fi...",com.twh010.farm.sort.small_pack,9.99,1786033241,40
3,2026-08-05,1785944084421732,8c5830ca411ff94bfd6488f6a5a8ae32,1782961079809000,Samsung,SM-F741U,Android 16,\N,45852b96-4381-417a-a356-be7daea32a47,-25200,...,Non-organic,applovin_int,\N,\N,\N,"firebase_exp_abt_26:0,firebase_exp_abt_34:0,fi...",com.twh010.farm.sort.small_pack,9.99,1785940039,39
4,2026-08-09,1786330310580634,7a8186f4e243b5b18719d9985fc01857,1783262903337000,Samsung,SM-S918U,Android 16,\N,766b8a88-dd8d-4a54-b9d4-a9211c70afe1,-25200,...,Non-organic,applovin_int,TWH010a_T5_D28_Jul04_tier1_Quang_ALV,\N,\N,"firebase_exp_abt_42:0,firebase_exp_abt_40:1,fi...",com.twh010.farm.sort.small_pack,9.99,1786326638,33

================================================================================
level_end.csv

,event_date,event_timestamp,user_pseudo_id,user_first_touch_timestamp,mobile_brand_name,mobile_model_name,operating_system_version,vendor_id,advertising_id,time_zone_offset_seconds,...,revive,booster_0,booster_1,booster_2,booster_3,unsolved_items,total_items,move,ga_session_id,ga_session_number
0,2026-08-02,1785659814450386,1106da443dcc988763e77ce7d4b8471f,1785659332441000,Samsung,SM-S926U,Android 16,\N,00000000-0000-0000-0000-000000000000,-14400,...,0,\N,\N,\N,\N,0,6,17,1785659332,1
1,2026-08-02,1785659487055386,1106da443dcc988763e77ce7d4b8471f,1785659332441000,Samsung,SM-S926U,Android 16,\N,00000000-0000-0000-0000-000000000000,-14400,...,0,\N,\N,\N,\N,0,4,14,1785659332,1
2,2026-08-06,1786082500044788,daab751ae77c1ecf9c17a8ccf385308d,1785690691037000,Samsung,SM-S926U,Android 16,\N,3c247802-a351-45dc-b4c6-bf6ab60fda80,-21600,...,1,\N,\N,\N,\N,0,7,25,1786078049,11
3,2026-08-07,1786143033824774,daab751ae77c1ecf9c17a8ccf385308d,1785690691037000,Samsung,SM-S926U,Android 16,\N,3c247802-a351-45dc-b4c6-bf6ab60fda80,-21600,...,0,\N,\N,\N,\N,0,9,32,1786141787,13
4,2026-08-06,1786078108746475,daab751ae77c1ecf9c17a8ccf385308d,1785690691037000,Samsung,SM-S926U,Android 16,\N,3c247802-a351-45dc-b4c6-bf6ab60fda80,-21600,...,0,\N,\N,\N,\N,8,8,18,1786078049,11

================================================================================
level_start.csv

,event_date,event_timestamp,user_pseudo_id,user_first_touch_timestamp,mobile_brand_name,mobile_model_name,operating_system_version,vendor_id,advertising_id,time_zone_offset_seconds,...,media_source,campaign,adset,adgroup_id,ab_test,level_id,attempt,level_index,ga_session_id,ga_session_number
0,2026-08-11,1786435230695120,e0aa291a76db2cce809da84208e472f7,1786433481577000,Samsung,SM-S928B,Android 16,\N,9824196e-6820-474c-88c1-3962cbb923a8,7200,...,\N,\N,\N,\N,"firebase_exp_abt_30:0,firebase_exp_abt_40:0,fi...",26,1,26,1786433481,1
1,2026-08-11,1786436956567443,e0aa291a76db2cce809da84208e472f7,1786433481577000,Samsung,SM-S928B,Android 16,\N,9824196e-6820-474c-88c1-3962cbb923a8,7200,...,\N,\N,\N,\N,"firebase_exp_abt_42:1,firebase_exp_abt_26:0,fi...",35,1,35,1786433481,1
2,2026-08-11,1786434283078147,e0aa291a76db2cce809da84208e472f7,1786433481577000,Samsung,SM-S928B,Android 16,\N,9824196e-6820-474c-88c1-3962cbb923a8,7200,...,\N,\N,\N,\N,"firebase_exp_abt_52:1,firebase_exp_abt_48:0,fi...",11,1,11,1786433481,1
3,2026-08-11,1786448966020772,5d4dc47a5eb5c81b4b994fba598f47c0,1786437964771000,Samsung,SM-S928B,Android 16,\N,c22509dd-6b59-49fc-906e-86bc93dcc8ff,7200,...,applovin_int,TWH010a_T5_D28_Jul04_tier1_Quang_ALV,\N,\N,"firebase_exp_abt_26:0,firebase_exp_abt_48:1,fi...",56,1,56,1786445141,2
4,2026-08-13,1786611036780966,5d4dc47a5eb5c81b4b994fba598f47c0,1786437964771000,Samsung,SM-S928B,Android 16,\N,c22509dd-6b59-49fc-906e-86bc93dcc8ff,7200,...,applovin_int,TWH010a_T5_D28_Jul04_tier1_Quang_ALV,\N,\N,"firebase_exp_abt_51:1,firebase_exp_abt_40:0,fi...",118,1,118,1786610772,10

================================================================================
buy_resource.csv

,event_date,event_timestamp,user_pseudo_id,user_first_touch_timestamp,mobile_brand_name,mobile_model_name,operating_system_version,vendor_id,advertising_id,time_zone_offset_seconds,...,ab_test,item_category,item_id,source,source_detail,source_id,value,value_balance,ga_session_id,ga_session_number
0,2026-08-06,1786059569479343,37a124124317ddde48a42b19caed5e06,1780890442327000,Samsung,SM-S916U,Android 16,\N,aabd26bc-b8a7-43a9-afa9-9119674e8dbc,-18000,...,"firebase_exp_abt_51:0,firebase_exp_abt_26:0,fi...",\N,\N,\N,\N,small_pack,2,3,1786059282,144
1,2026-08-06,1786059904758166,37a124124317ddde48a42b19caed5e06,1780890442327000,Samsung,SM-S916U,Android 16,\N,aabd26bc-b8a7-43a9-afa9-9119674e8dbc,-18000,...,"firebase_exp_abt_42:1,firebase_exp_abt_40:0,fi...",\N,\N,\N,\N,small_pack,2,4,1786059282,144
2,2026-08-06,1786059569450343,37a124124317ddde48a42b19caed5e06,1780890442327000,Samsung,SM-S916U,Android 16,\N,aabd26bc-b8a7-43a9-afa9-9119674e8dbc,-18000,...,"firebase_exp_abt_30:0,firebase_exp_abt_46:0,fi...",\N,\N,\N,\N,small_pack,2,8,1786059282,144
3,2026-08-06,1786059904737166,37a124124317ddde48a42b19caed5e06,1780890442327000,Samsung,SM-S916U,Android 16,\N,aabd26bc-b8a7-43a9-afa9-9119674e8dbc,-18000,...,"firebase_exp_abt_30:0,firebase_exp_abt_48:0,fi...",\N,\N,\N,\N,small_pack,2,10,1786059282,144
4,2026-08-06,1786059904789166,37a124124317ddde48a42b19caed5e06,1780890442327000,Samsung,SM-S916U,Android 16,\N,aabd26bc-b8a7-43a9-afa9-9119674e8dbc,-18000,...,"firebase_exp_abt_48:0,firebase_exp_abt_30:0,fi...",\N,\N,\N,\N,small_pack,2,47,1786059282,144

## 3. Data Quality Audit

In [72]:
date_ranges = []

for f in csv_files:
    try:
        result = con.execute(f"""
        SELECT
            MIN(event_date) AS min_date,
            MAX(event_date) AS max_date
        FROM read_csv_auto('{data_path}/{f}')
        """).df()

        date_ranges.append({
            "file": f,
            "min_date": result.loc[0, "min_date"],
            "max_date": result.loc[0, "max_date"]
        })

    except Exception as e:
        print(f, e)

pd.DataFrame(date_ranges)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

                           file   min_date   max_date
0             ad_impression.csv 2026-07-29 2026-08-24
1    winstreak_point_gained.csv 2026-07-29 2026-08-25
2             earn_resource.csv 2026-07-29 2026-08-25
3            spend_resource.csv 2026-07-29 2026-08-25
4  winstreak_reward_claimed.csv 2026-07-29 2026-08-25
5           in_app_purchase.csv 2026-07-31 2026-08-24
6                 level_end.csv 2026-07-29 2026-08-24
7               level_start.csv 2026-07-29 2026-08-24
8              buy_resource.csv 2026-07-31 2026-08-25

Số user unique mỗi bảng

In [73]:
user_counts = []

for f in csv_files:
    try:
        n = con.execute(f"""
        SELECT COUNT(DISTINCT user_pseudo_id)
        FROM read_csv_auto('{data_path}/{f}')
        """).fetchone()[0]

        user_counts.append({
            "file": f,
            "unique_users": n
        })

    except Exception as e:
        print(f, e)

pd.DataFrame(user_counts)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

                           file  unique_users
0             ad_impression.csv         12935
1    winstreak_point_gained.csv          9345
2             earn_resource.csv         19345
3            spend_resource.csv         15119
4  winstreak_reward_claimed.csv          8728
5           in_app_purchase.csv           455
6                 level_end.csv         19567
7               level_start.csv         19890
8              buy_resource.csv           586

Kiểm tra level_start

In [74]:
con.execute(f"""
SELECT
    COUNT(*) AS rows,
    COUNT(DISTINCT user_pseudo_id) AS users,
    MIN(level_id) AS min_level,
    MAX(level_id) AS max_level,
    MIN(attempt) AS min_attempt,
    MAX(attempt) AS max_attempt
FROM read_csv_auto('{data_path}/level_start.csv')
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

      rows  users  min_level  max_level  min_attempt  max_attempt
0  1287663  19890          1        500            1          118

In [75]:
con.execute(f"""
SELECT
    COUNT(*) AS total_rows,
    SUM(CASE WHEN level_id != level_index THEN 1 ELSE 0 END) AS mismatch_rows
FROM read_csv_auto('{data_path}/level_start.csv')
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   total_rows  mismatch_rows
0     1287663        32635.0

Phân phối attempt

In [76]:
con.execute(f"""
SELECT
    attempt,
    COUNT(*) AS attempts_count
FROM read_csv_auto('{data_path}/level_start.csv')
GROUP BY attempt
ORDER BY attempt
LIMIT 30
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

    attempt  attempts_count
0         1          929698
1         2          166681
2         3           73843
3         4           39685
4         5           23638
5         6           14978
6         7            9997
7         8            6857
8         9            4842
9        10            3572
10       11            2707
11       12            2043
12       13            1598
13       14            1238
14       15             978
15       16             797
16       17             635
17       18             525
18       19             443
19       20             358
20       21             301
21       22             252
22       23             205
23       24             179
24       25             158
25       26             135
26       27             114
27       28              95
28       29              83
29       30              78

In [77]:
level_end_columns = con.execute(f"""
DESCRIBE
SELECT *
FROM read_csv_auto('{data_path}/level_end.csv')
""").df()

pd.set_option("display.max_rows", 100)
level_end_columns[["column_name", "column_type"]]

                   column_name column_type
0                   event_date        DATE
1              event_timestamp      BIGINT
2               user_pseudo_id     VARCHAR
3   user_first_touch_timestamp      BIGINT
4            mobile_brand_name     VARCHAR
5            mobile_model_name     VARCHAR
6     operating_system_version     VARCHAR
7                    vendor_id     VARCHAR
8               advertising_id     VARCHAR
9     time_zone_offset_seconds      BIGINT
10                     country     VARCHAR
11                        city     VARCHAR
12                 app_version     VARCHAR
13              install_source     VARCHAR
14         traffic_source_name     VARCHAR
15       traffic_source_medium     VARCHAR
16              traffic_source     VARCHAR
17                    platform     VARCHAR
18                appsflyer_id     VARCHAR
19                   player_id     VARCHAR
20                   max_level      BIGINT
21                   iap_count      BIGINT
22              rewarded_count      BIGINT
23                 inter_count      BIGINT
24                coin_balance      BIGINT
25                  coin_total      BIGINT
26                        life     VARCHAR
27                   af_status     VARCHAR
28                media_source     VARCHAR
29                    campaign     VARCHAR
30                       adset     VARCHAR
31                  adgroup_id     VARCHAR
32                     ab_test     VARCHAR
33                    level_id      BIGINT
34                 level_index      BIGINT
35                     attempt      BIGINT
36                      status      BIGINT
37                    playtime      BIGINT
38                      revive      BIGINT
39                   booster_0     VARCHAR
40                   booster_1     VARCHAR
41                   booster_2     VARCHAR
42                   booster_3     VARCHAR
43              unsolved_items      BIGINT
44                 total_items      BIGINT
45                        move      BIGINT
46               ga_session_id      BIGINT
47           ga_session_number      BIGINT

In [78]:
con.execute(f"""
SELECT
    status,
    COUNT(*) AS rows,
    COUNT(DISTINCT user_pseudo_id) AS users,
    AVG(unsolved_items) AS avg_unsolved_items,
    AVG(total_items) AS avg_total_items,
    AVG(move) AS avg_move,
    AVG(playtime) AS avg_playtime,
    AVG(revive) AS avg_revive
FROM read_csv_auto('{data_path}/level_end.csv')
GROUP BY status
ORDER BY status
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,status,rows,users,avg_unsolved_items,avg_total_items,avg_move,avg_playtime,avg_revive
0,-1,1737,1151,6.895797,7.477260,10.221071,71.841105,0.071963
1,0,260545,11368,9.201789,9.992615,16.941515,77.665386,0.240097
2,1,922994,19408,0.055407,8.453071,29.849469,113.329987,0.189541
3,2,28633,4934,9.071596,9.984913,18.782384,118.136626,0.166242

In [79]:
con.execute(f"""
SELECT
    level_id,
    level_index,
    COUNT(*) AS rows
FROM read_csv_auto('{data_path}/level_start.csv')
WHERE level_id != level_index
GROUP BY level_id, level_index
ORDER BY rows DESC
LIMIT 30
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

    level_id  level_index  rows
0        444          462    39
1        467          485    37
2        419          437    31
3        496          542    30
4        471          555    30
5        349          515    28
6        434          463    28
7        430          448    28
8        494          512    26
9        434          452    25
10       484          550    24
11       430          639    23
12       431          664    22
13       497          515    22
14       489          507    22
15       339          596    22
16       430          522    22
17       309          532    21
18       223          389    21
19       409          427    21
20       409          448    21
21       394          545    20
22       394          613    20
23       487          526    20
24       492          744    20
25       427          445    20
26       430          459    19
27       409          422    19
28       479          503    19
29       419          478    19

In [80]:
con.execute(f"""
SELECT
    COUNT(*) AS total_rows,

    COUNT(DISTINCT
        user_pseudo_id || '|' ||
        CAST(level_index AS VARCHAR) || '|' ||
        CAST(attempt AS VARCHAR)
    ) AS unique_by_level_index,

    COUNT(DISTINCT
        user_pseudo_id || '|' ||
        CAST(level_id AS VARCHAR) || '|' ||
        CAST(attempt AS VARCHAR)
    ) AS unique_by_level_id

FROM read_csv_auto('{data_path}/level_end.csv')
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   total_rows  unique_by_level_index  unique_by_level_id
0     1213909                1198424             1190007

### Duplicate Event Check

In [81]:
con.execute(f"""
SELECT
    COUNT(*) AS total_rows,

    COUNT(DISTINCT
        user_pseudo_id || '|' ||
        CAST(level_index AS VARCHAR) || '|' ||
        CAST(attempt AS VARCHAR)
    ) AS unique_keys,

    COUNT(*) -
    COUNT(DISTINCT
        user_pseudo_id || '|' ||
        CAST(level_index AS VARCHAR) || '|' ||
        CAST(attempt AS VARCHAR)
    ) AS duplicate_excess

FROM read_csv_auto('{data_path}/level_start.csv')
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   total_rows  unique_keys  duplicate_excess
0     1287663      1271863             15800

xem các duplicate

In [82]:
con.execute(f"""
SELECT
    user_pseudo_id,
    level_index,
    attempt,
    COUNT(*) AS n
FROM read_csv_auto('{data_path}/level_start.csv')
GROUP BY 1,2,3
HAVING COUNT(*) > 1
ORDER BY n DESC
LIMIT 30
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

                      user_pseudo_id  level_index  attempt   n
0   857ddaf1e4cf4c0bb5c701239bf5b185           31        1  10
1   857ddaf1e4cf4c0bb5c701239bf5b185           29        1  10
2   857ddaf1e4cf4c0bb5c701239bf5b185           33        1  10
3   857ddaf1e4cf4c0bb5c701239bf5b185           28        1  10
4   857ddaf1e4cf4c0bb5c701239bf5b185           34        1  10
5   857ddaf1e4cf4c0bb5c701239bf5b185           36        1  10
6   857ddaf1e4cf4c0bb5c701239bf5b185           30        1  10
7   857ddaf1e4cf4c0bb5c701239bf5b185           32        1  10
8   857ddaf1e4cf4c0bb5c701239bf5b185           27        1  10
9   857ddaf1e4cf4c0bb5c701239bf5b185           35        1  10
10  857ddaf1e4cf4c0bb5c701239bf5b185           39        1   9
11  857ddaf1e4cf4c0bb5c701239bf5b185            8        1   9
12  857ddaf1e4cf4c0bb5c701239bf5b185           48        1   9
13  857ddaf1e4cf4c0bb5c701239bf5b185           25        1   9
14  857ddaf1e4cf4c0bb5c701239bf5b185           47        1   9
15  857ddaf1e4cf4c0bb5c701239bf5b185           41        1   9
16  857ddaf1e4cf4c0bb5c701239bf5b185           43        1   9
17  857ddaf1e4cf4c0bb5c701239bf5b185           10        1   9
18  857ddaf1e4cf4c0bb5c701239bf5b185           51        1   9
19  857ddaf1e4cf4c0bb5c701239bf5b185           15        1   9
20  857ddaf1e4cf4c0bb5c701239bf5b185           38        1   9
21  857ddaf1e4cf4c0bb5c701239bf5b185           40        1   9
22  857ddaf1e4cf4c0bb5c701239bf5b185           12        1   9
23  857ddaf1e4cf4c0bb5c701239bf5b185           11        1   9
24  857ddaf1e4cf4c0bb5c701239bf5b185           14        1   9
25  857ddaf1e4cf4c0bb5c701239bf5b185           52        1   9
26  857ddaf1e4cf4c0bb5c701239bf5b185           26        1   9
27  857ddaf1e4cf4c0bb5c701239bf5b185           24        1   9
28  857ddaf1e4cf4c0bb5c701239bf5b185           49        1   9
29  857ddaf1e4cf4c0bb5c701239bf5b185           45        1   9

In [83]:
con.execute(f"""
SELECT
    user_pseudo_id,
    level_index,
    attempt,
    COUNT(*) AS n,
    MIN(event_timestamp) AS first_ts,
    MAX(event_timestamp) AS last_ts
FROM read_csv_auto('{data_path}/level_end.csv')
GROUP BY 1,2,3
HAVING COUNT(*) > 1
ORDER BY n DESC
LIMIT 30
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,user_pseudo_id,level_index,attempt,n,first_ts,last_ts
0,857ddaf1e4cf4c0bb5c701239bf5b185,31,1,10,1785665581784186,1786523463737466
1,857ddaf1e4cf4c0bb5c701239bf5b185,34,1,10,1785665908470627,1786523721616220
2,857ddaf1e4cf4c0bb5c701239bf5b185,33,1,10,1785665803416186,1786523607876466
3,857ddaf1e4cf4c0bb5c701239bf5b185,30,1,10,1785665490094186,1786523384418466
4,857ddaf1e4cf4c0bb5c701239bf5b185,29,1,10,1785665338603065,1786523317021466
5,857ddaf1e4cf4c0bb5c701239bf5b185,27,1,10,1785665247522065,1786523159956466
6,857ddaf1e4cf4c0bb5c701239bf5b185,28,1,10,1785665299876065,1786523238575466
7,857ddaf1e4cf4c0bb5c701239bf5b185,32,1,10,1785665706041186,1786523531389466
8,857ddaf1e4cf4c0bb5c701239bf5b185,42,1,9,1785666550569746,1786524620608873
9,857ddaf1e4cf4c0bb5c701239bf5b185,41,1,9,1785666496142746,1786524557215220
10,857ddaf1e4cf4c0bb5c701239bf5b185,15,1,9,1785714309399473,1786522341574516
11,857ddaf1e4cf4c0bb5c701239bf5b185,37,1,9,1785666221903627,1786524252928220
12,857ddaf1e4cf4c0bb5c701239bf5b185,10,1,9,1785714042091926,1786522013246516
13,857ddaf1e4cf4c0bb5c701239bf5b185,51,1,9,1785667483088907,1786525818830238
14,857ddaf1e4cf4c0bb5c701239bf5b185,25,1,9,1785715029718730,1786522985281466
15,857ddaf1e4cf4c0bb5c701239bf5b185,35,1,9,1785666021167627,1786523914813220
16,857ddaf1e4cf4c0bb5c701239bf5b185,50,1,9,1785667359787907,1786525682426873
17,857ddaf1e4cf4c0bb5c701239bf5b185,8,1,9,1785713966205926,1786521925764506
18,857ddaf1e4cf4c0bb5c701239bf5b185,39,1,9,1785666386040746,1786524426804220
19,857ddaf1e4cf4c0bb5c701239bf5b185,47,1,9,1785667031112607,1786525406604873
20,857ddaf1e4cf4c0bb5c701239bf5b185,13,1,9,1785714214401926,1786522240913516
21,857ddaf1e4cf4c0bb5c701239bf5b185,11,1,9,1785714093513926,1786522076095516
22,857ddaf1e4cf4c0bb5c701239bf5b185,49,1,9,1785667242241907,1786525603472873
23,857ddaf1e4cf4c0bb5c701239bf5b185,45,1,9,1785666863612607,1786525232982873
24,857ddaf1e4cf4c0bb5c701239bf5b185,9,1,9,1785714003122926,1786521957608506
25,857ddaf1e4cf4c0bb5c701239bf5b185,44,1,9,1785666768375607,1786524882450873
26,857ddaf1e4cf4c0bb5c701239bf5b185,46,1,9,1785666916138607,1786525295521873
27,857ddaf1e4cf4c0bb5c701239bf5b185,26,1,9,1785715080386730,1786523057455466
28,857ddaf1e4cf4c0bb5c701239bf5b185,14,1,9,1785714260272926,1786522300120516
29,857ddaf1e4cf4c0bb5c701239bf5b185,52,1,9,1785667560477526,1786525899066238

### Status Validation

To validate the meaning of `status`, I compared outcome patterns and subsequent player behavior across status values.

The analysis strongly supports `status = 1` as a successful level completion. Other status values (`0`, `2`, and `-1`) are therefore treated conservatively as non-win outcomes rather than being assigned specific meanings without documentation.

In [84]:
con.execute(f"""
SELECT
    status,

    COUNT(*) AS rows,

    SUM(CASE WHEN unsolved_items = 0 THEN 1 ELSE 0 END) AS solved_rows,

    ROUND(
        100.0 * SUM(CASE WHEN unsolved_items = 0 THEN 1 ELSE 0 END)
        / COUNT(*),
        2
    ) AS solved_pct,

    AVG(playtime) AS avg_playtime,
    AVG(move) AS avg_move,
    AVG(revive) AS avg_revive

FROM read_csv_auto('{data_path}/level_end.csv')

GROUP BY status
ORDER BY status
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,status,rows,solved_rows,solved_pct,avg_playtime,avg_move,avg_revive
0,-1,1737,80.0,4.61,71.841105,10.221071,0.071963
1,0,260545,0.0,0.00,77.665386,16.941515,0.240097
2,1,922994,898194.0,97.31,113.329987,29.849469,0.189541
3,2,28633,164.0,0.57,118.136626,18.782384,0.166242

In [85]:
status_behavior = con.execute(f"""
WITH all_events AS (

    SELECT
        user_pseudo_id,
        event_timestamp,
        level_index,
        status,
        'end' AS event_type
    FROM read_csv_auto('{data_path}/level_end.csv')

    UNION ALL

    SELECT
        user_pseudo_id,
        event_timestamp,
        level_index,
        NULL AS status,
        'start' AS event_type
    FROM read_csv_auto('{data_path}/level_start.csv')
),

ordered AS (
    SELECT
        *,
        LEAD(event_type) OVER (
            PARTITION BY user_pseudo_id
            ORDER BY event_timestamp
        ) AS next_event_type,

        LEAD(level_index) OVER (
            PARTITION BY user_pseudo_id
            ORDER BY event_timestamp
        ) AS next_level_index

    FROM all_events
)

SELECT
    status,
    COUNT(*) AS rows,

    ROUND(
        100.0 * SUM(
            CASE
                WHEN next_event_type = 'start'
                 AND next_level_index = level_index
                THEN 1 ELSE 0
            END
        ) / COUNT(*),
        2
    ) AS immediate_retry_pct,

    ROUND(
        100.0 * SUM(
            CASE
                WHEN next_event_type = 'start'
                 AND next_level_index = level_index + 1
                THEN 1 ELSE 0
            END
        ) / COUNT(*),
        2
    ) AS immediate_next_level_pct

FROM ordered
WHERE event_type = 'end'

GROUP BY status
ORDER BY status
""").df()

status_behavior

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   status    rows  immediate_retry_pct  immediate_next_level_pct
0      -1    1737                91.71                      0.40
1       0  260545                97.68                      0.03
2       1  922994                 0.00                     97.66
3       2   28633                97.55                      0.00

In [86]:
con.execute(f"""
SELECT
    status,
    COUNT(*) AS rows,

    ROUND(AVG(attempt), 2) AS avg_attempt,
    ROUND(AVG(playtime), 2) AS avg_playtime,
    ROUND(AVG(move), 2) AS avg_move,
    ROUND(AVG(revive), 3) AS avg_revive,
    ROUND(AVG(unsolved_items), 2) AS avg_unsolved,

    ROUND(
        100.0 * SUM(CASE WHEN revive > 0 THEN 1 ELSE 0 END)
        / COUNT(*),
        2
    ) AS revive_used_pct

FROM read_csv_auto('{data_path}/level_end.csv')

GROUP BY status
ORDER BY status
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,status,rows,avg_attempt,avg_playtime,avg_move,avg_revive,avg_unsolved,revive_used_pct
0,-1,1737,2.17,71.84,10.22,0.072,6.90,7.14
1,0,260545,2.89,77.67,16.94,0.240,9.20,23.90
2,1,922994,1.38,113.33,29.85,0.190,0.06,18.05
3,2,28633,2.92,118.14,18.78,0.166,9.07,16.48

In [87]:
con.execute(f"""
SELECT
    status,

    ROUND(
        100.0 * SUM(
            CASE
                WHEN NULLIF(booster_0, '\\N') IS NOT NULL
                  OR NULLIF(booster_1, '\\N') IS NOT NULL
                  OR NULLIF(booster_2, '\\N') IS NOT NULL
                  OR NULLIF(booster_3, '\\N') IS NOT NULL
                THEN 1 ELSE 0
            END
        ) / COUNT(*),
        2
    ) AS booster_used_pct

FROM read_csv_auto('{data_path}/level_end.csv')

GROUP BY status
ORDER BY status
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   status  booster_used_pct
0      -1              3.86
1       0              3.15
2       1              8.83
3       2              6.85

In [88]:
for col in ["booster_0", "booster_1", "booster_2", "booster_3"]:
    print("\n", col)
    display(
        con.execute(f"""
        SELECT
            {col},
            COUNT(*) AS rows
        FROM read_csv_auto('{data_path}/level_end.csv')
        GROUP BY {col}
        ORDER BY rows DESC
        LIMIT 20
        """).df()
    )

 booster_0

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  booster_0     rows
0        \N  1206562
1         1     6261
2         2      855
3         3      174
4         4       45
5         5        7
6         6        3
7        17        1
8         8        1

 booster_1

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   booster_1     rows
0         \N  1187463
1          1    23128
2          2     2511
3          3      584
4          4      142
5          5       49
6          6       19
7          7        6
8          8        3
9         10        2
10        11        2

 booster_2

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  booster_2     rows
0        \N  1173142
1         1    36989
2         2     3277
3         3      379
4         4       60
5         6       25
6         5       24
7         7        5
8         8        5
9         9        3

 booster_3

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   booster_3     rows
0         \N  1188712
1          1    24741
2          2      373
3          9       21
4          3       19
5         10       10
6          8        9
7          4        7
8          5        7
9          7        5
10         6        4
11        11        1

In [89]:
# 1. Duplicate candidate key ở level_start
con.execute(f"""
SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT
        user_pseudo_id || '|' ||
        CAST(level_index AS VARCHAR) || '|' ||
        CAST(attempt AS VARCHAR)
    ) AS unique_keys
FROM read_csv_auto('{data_path}/level_start.csv')
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   total_rows  unique_keys
0     1287663      1271863

In [90]:
# 2. Top duplicate ở level_start
con.execute(f"""
SELECT
    user_pseudo_id,
    level_index,
    attempt,
    COUNT(*) AS n
FROM read_csv_auto('{data_path}/level_start.csv')
GROUP BY 1,2,3
HAVING COUNT(*) > 1
ORDER BY n DESC
LIMIT 20
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

                      user_pseudo_id  level_index  attempt   n
0   857ddaf1e4cf4c0bb5c701239bf5b185           28        1  10
1   857ddaf1e4cf4c0bb5c701239bf5b185           27        1  10
2   857ddaf1e4cf4c0bb5c701239bf5b185           33        1  10
3   857ddaf1e4cf4c0bb5c701239bf5b185           35        1  10
4   857ddaf1e4cf4c0bb5c701239bf5b185           34        1  10
5   857ddaf1e4cf4c0bb5c701239bf5b185           36        1  10
6   857ddaf1e4cf4c0bb5c701239bf5b185           31        1  10
7   857ddaf1e4cf4c0bb5c701239bf5b185           29        1  10
8   857ddaf1e4cf4c0bb5c701239bf5b185           32        1  10
9   857ddaf1e4cf4c0bb5c701239bf5b185           30        1  10
10  857ddaf1e4cf4c0bb5c701239bf5b185           44        1   9
11  857ddaf1e4cf4c0bb5c701239bf5b185           49        1   9
12  857ddaf1e4cf4c0bb5c701239bf5b185           39        1   9
13  857ddaf1e4cf4c0bb5c701239bf5b185           25        1   9
14  857ddaf1e4cf4c0bb5c701239bf5b185           38        1   9
15  857ddaf1e4cf4c0bb5c701239bf5b185           46        1   9
16  857ddaf1e4cf4c0bb5c701239bf5b185           13        1   9
17  857ddaf1e4cf4c0bb5c701239bf5b185           43        1   9
18  857ddaf1e4cf4c0bb5c701239bf5b185           53        1   9
19  857ddaf1e4cf4c0bb5c701239bf5b185            9        1   9

In [91]:
# 3. Top duplicate ở level_end
con.execute(f"""
SELECT
    user_pseudo_id,
    level_index,
    attempt,
    COUNT(*) AS n,
    COUNT(DISTINCT status) AS distinct_status,
    MIN(event_timestamp) AS first_ts,
    MAX(event_timestamp) AS last_ts
FROM read_csv_auto('{data_path}/level_end.csv')
GROUP BY 1,2,3
HAVING COUNT(*) > 1
ORDER BY n DESC
LIMIT 20
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,user_pseudo_id,level_index,attempt,n,distinct_status,first_ts,last_ts
0,857ddaf1e4cf4c0bb5c701239bf5b185,33,1,10,1,1785665803416186,1786523607876466
1,857ddaf1e4cf4c0bb5c701239bf5b185,28,1,10,1,1785665299876065,1786523238575466
2,857ddaf1e4cf4c0bb5c701239bf5b185,27,1,10,1,1785665247522065,1786523159956466
3,857ddaf1e4cf4c0bb5c701239bf5b185,29,1,10,2,1785665338603065,1786523317021466
4,857ddaf1e4cf4c0bb5c701239bf5b185,31,1,10,1,1785665581784186,1786523463737466
5,857ddaf1e4cf4c0bb5c701239bf5b185,30,1,10,1,1785665490094186,1786523384418466
6,857ddaf1e4cf4c0bb5c701239bf5b185,34,1,10,1,1785665908470627,1786523721616220
7,857ddaf1e4cf4c0bb5c701239bf5b185,32,1,10,2,1785665706041186,1786523531389466
8,857ddaf1e4cf4c0bb5c701239bf5b185,42,1,9,1,1785666550569746,1786524620608873
9,857ddaf1e4cf4c0bb5c701239bf5b185,45,1,9,2,1785666863612607,1786525232982873
10,857ddaf1e4cf4c0bb5c701239bf5b185,26,1,9,1,1785715080386730,1786523057455466
11,857ddaf1e4cf4c0bb5c701239bf5b185,52,1,9,1,1785667560477526,1786525899066238
12,857ddaf1e4cf4c0bb5c701239bf5b185,46,1,9,1,1785666916138607,1786525295521873
13,857ddaf1e4cf4c0bb5c701239bf5b185,41,1,9,1,1785666496142746,1786524557215220
14,857ddaf1e4cf4c0bb5c701239bf5b185,11,1,9,1,1785714093513926,1786522076095516
15,857ddaf1e4cf4c0bb5c701239bf5b185,47,1,9,1,1785667031112607,1786525406604873
16,857ddaf1e4cf4c0bb5c701239bf5b185,8,1,9,1,1785713966205926,1786521925764506
17,857ddaf1e4cf4c0bb5c701239bf5b185,35,1,9,1,1785666021167627,1786523914813220
18,857ddaf1e4cf4c0bb5c701239bf5b185,15,1,9,1,1785714309399473,1786522341574516
19,857ddaf1e4cf4c0bb5c701239bf5b185,10,1,9,1,1785714042091926,1786522013246516

In [92]:
dup_user = "857ddaf1e4cf4c0bb5c701239bf5b185"

con.execute(f"""
SELECT
    event_date,
    TRY_CAST(event_timestamp AS BIGINT) AS event_timestamp,
    level_id,
    level_index,
    attempt,
    ga_session_id,
    ga_session_number
FROM read_csv_auto(
    '{data_path}/level_start.csv',
    all_varchar = true,
    nullstr = '\\N'
)
WHERE user_pseudo_id = '{dup_user}'
ORDER BY TRY_CAST(event_timestamp AS BIGINT)
LIMIT 300
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,event_date,event_timestamp,level_id,level_index,attempt,ga_session_id,ga_session_number
0,2026-08-02,1785665148309065,26,26,2,1785665134,45
1,2026-08-02,1785665191218065,27,27,1,1785665134,45
2,2026-08-02,1785665255474065,28,28,1,1785665134,45
3,2026-08-02,1785665307279065,29,29,1,1785665134,45
4,2026-08-02,1785665340241065,29,29,2,1785665134,45
...,...,...,...,...,...,...,...
295,2026-08-04,1785886730854673,89,89,1,1785883497,53
296,2026-08-04,1785886874426673,90,90,1,1785883497,53
297,2026-08-04,1785886951271673,91,91,1,1785883497,53
298,2026-08-04,1785887038696857,92,92,1,1785883497,53
299,2026-08-04,1785887143816857,93,93,1,1785883497,53

In [93]:
con.execute(f"""
SELECT
    event_date,
    TRY_CAST(event_timestamp AS BIGINT) AS event_timestamp,
    level_id,
    level_index,
    attempt,
    status,
    playtime,
    unsolved_items,
    ga_session_id,
    ga_session_number
FROM read_csv_auto(
    '{data_path}/level_end.csv',
    all_varchar = true,
    nullstr = '\\N'
)
WHERE user_pseudo_id = '{dup_user}'
ORDER BY TRY_CAST(event_timestamp AS BIGINT)
LIMIT 300
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,event_date,event_timestamp,level_id,level_index,attempt,status,playtime,unsolved_items,ga_session_id,ga_session_number
0,2026-08-02,1785665181627065,26,26,2,1,33,0,1785665134,45
1,2026-08-02,1785665247522065,27,27,1,1,56,0,1785665134,45
2,2026-08-02,1785665299876065,28,28,1,1,44,0,1785665134,45
3,2026-08-02,1785665338603065,29,29,1,0,29,5,1785665134,45
4,2026-08-02,1785665404604065,29,29,2,1,64,0,1785665134,45
...,...,...,...,...,...,...,...,...,...,...
295,2026-08-04,1785888063934654,97,97,1,1,93,0,1785883497,53
296,2026-08-04,1785888361060654,98,98,1,1,110,0,1785883497,53
297,2026-08-04,1785888507001654,99,99,1,1,92,0,1785883497,53
298,2026-08-04,1785888600407258,100,100,1,1,54,0,1785883497,53
299,2026-08-04,1785888734274258,101,101,1,1,104,0,1785883497,53

In [94]:
# Tạo level_start.parquet chỉ với các cột cần thiết
con.execute(f"""
COPY (
    SELECT
        TRY_CAST(event_timestamp AS BIGINT) AS start_ts,
        user_pseudo_id,
        TRY_CAST(level_id AS BIGINT) AS level_id,
        TRY_CAST(level_index AS BIGINT) AS level_index,
        TRY_CAST(attempt AS BIGINT) AS attempt,
        TRY_CAST(ga_session_id AS BIGINT) AS ga_session_id
    FROM read_csv_auto(
        '{data_path}/level_start.csv',
        all_varchar=true,
        nullstr='\\N'
    )
)
TO '/content/level_start.parquet'
(FORMAT PARQUET)
""")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [95]:
con.execute(f"""
COPY (
    SELECT
        TRY_CAST(event_timestamp AS BIGINT) AS end_ts,
        user_pseudo_id,
        TRY_CAST(level_id AS BIGINT) AS level_id,
        TRY_CAST(level_index AS BIGINT) AS level_index,
        TRY_CAST(attempt AS BIGINT) AS attempt,
        TRY_CAST(status AS BIGINT) AS status,
        TRY_CAST(playtime AS BIGINT) AS playtime,
        TRY_CAST(revive AS BIGINT) AS revive,
        TRY_CAST(unsolved_items AS BIGINT) AS unsolved_items,
        TRY_CAST(total_items AS BIGINT) AS total_items,
        TRY_CAST(move AS BIGINT) AS move
    FROM read_csv_auto(
        '{data_path}/level_end.csv',
        all_varchar=true,
        nullstr='\\N'
    )
)
TO '/content/level_end.parquet'
(FORMAT PARQUET)
""")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [96]:
con.execute("""
SELECT
    COUNT(*) AS rows,
    COUNT(DISTINCT user_pseudo_id) AS users,
    MIN(level_index) AS min_level,
    MAX(level_index) AS max_level
FROM '/content/level_start.parquet'
""").df()

      rows  users  min_level  max_level
0  1287663  19890          1       2971

In [97]:
con.execute("""
SELECT
    COUNT(*) AS total_rows,
    SUM(CASE WHEN level_index > 500 THEN 1 ELSE 0 END) AS rows_over_500,
    COUNT(DISTINCT CASE WHEN level_index > 500 THEN user_pseudo_id END) AS users_over_500,
    MIN(CASE WHEN level_index > 500 THEN level_index END) AS min_over_500,
    MAX(level_index) AS max_level
FROM '/content/level_start.parquet'
""").df()

   total_rows  rows_over_500  users_over_500  min_over_500  max_level
0     1287663        28178.0             122           501       2971

In [98]:
con.execute("""
SELECT
    level_index,
    COUNT(*) AS starts,
    COUNT(DISTINCT user_pseudo_id) AS users
FROM '/content/level_start.parquet'
WHERE level_index > 500
GROUP BY level_index
ORDER BY level_index
LIMIT 50
""").df()

    level_index  starts  users
0           501     141     89
1           502     163     88
2           503     183     91
3           504     145     91
4           505     141     90
5           506     113     87
6           507     155     90
7           508     176     89
8           509     143     86
9           510     136     86
10          511     132     85
11          512     145     85
12          513     124     82
13          514     135     83
14          515     170     83
15          516     147     84
16          517     130     85
17          518     146     84
18          519     131     80
19          520     135     78
20          521     131     79
21          522     138     80
22          523     137     78
23          524     131     79
24          525     140     81
25          526     149     80
26          527     157     80
27          528     107     79
28          529     129     79
29          530     145     80
30          531     110     78
31          532     136     74
32          533     132     76
33          534     119     75
34          535     138     74
35          536     112     73
36          537     119     76
37          538     118     73
38          539     113     70
39          540     142     71
40          541     114     69
41          542     145     71
42          543     129     72
43          544      91     69
44          545     120     68
45          546      88     66
46          547      92     67
47          548     114     67
48          549      89     67
49          550     121     67

In [99]:
con.execute("""
SELECT
    user_pseudo_id,
    start_ts,
    level_id,
    level_index,
    attempt,
    ga_session_id
FROM '/content/level_start.parquet'
WHERE level_index > 500
ORDER BY level_index DESC
LIMIT 30
""").df()

,user_pseudo_id,start_ts,level_id,level_index,attempt,ga_session_id
0,a020a7482f29bf14b93d88fdbc4273ec,1786587710144109,319,2971,1,1786587324
1,a020a7482f29bf14b93d88fdbc4273ec,1786587576014598,236,2970,1,1786587324
2,a020a7482f29bf14b93d88fdbc4273ec,1786587462622598,200,2969,1,1786587324
3,a020a7482f29bf14b93d88fdbc4273ec,1786587339082598,313,2968,1,1786587324
4,a020a7482f29bf14b93d88fdbc4273ec,1786490921752763,222,2967,1,1786489724
5,a020a7482f29bf14b93d88fdbc4273ec,1786490809671763,374,2966,1,1786489724
6,a020a7482f29bf14b93d88fdbc4273ec,1786490673950763,476,2965,1,1786489724
7,a020a7482f29bf14b93d88fdbc4273ec,1786490547916353,142,2964,1,1786489724
8,a020a7482f29bf14b93d88fdbc4273ec,1786490413705353,339,2963,1,1786489724
9,a020a7482f29bf14b93d88fdbc4273ec,1786490287573353,103,2962,1,1786489724
10,a020a7482f29bf14b93d88fdbc4273ec,1786490208364353,141,2961,1,1786489724
11,a020a7482f29bf14b93d88fdbc4273ec,1786490101805102,412,2960,1,1786489724
12,a020a7482f29bf14b93d88fdbc4273ec,1786490003283102,361,2959,1,1786489724
13,a020a7482f29bf14b93d88fdbc4273ec,1786489869362102,384,2958,1,1786489724
14,a020a7482f29bf14b93d88fdbc4273ec,1786489734465321,237,2957,2,1786489724
15,a020a7482f29bf14b93d88fdbc4273ec,1786415663402223,237,2957,1,1786415548
16,a020a7482f29bf14b93d88fdbc4273ec,1786415562537223,418,2956,1,1786415548
17,a020a7482f29bf14b93d88fdbc4273ec,1786363353384735,159,2955,1,1786362616
18,a020a7482f29bf14b93d88fdbc4273ec,1786363186414205,235,2954,1,1786362616
19,a020a7482f29bf14b93d88fdbc4273ec,1786363062779205,203,2953,1,1786362616
20,a020a7482f29bf14b93d88fdbc4273ec,1786362963638318,342,2952,1,1786362616
21,a020a7482f29bf14b93d88fdbc4273ec,1786362782414318,433,2951,1,1786362616
22,a020a7482f29bf14b93d88fdbc4273ec,1786362630998318,164,2950,2,1786362616
23,a020a7482f29bf14b93d88fdbc4273ec,1786311658973251,164,2950,1,1786309659
24,a020a7482f29bf14b93d88fdbc4273ec,1786311566106792,473,2949,1,1786309659
25,a020a7482f29bf14b93d88fdbc4273ec,1786311428694792,180,2948,1,1786309659
26,a020a7482f29bf14b93d88fdbc4273ec,1786311270966792,479,2947,1,1786309659
27,a020a7482f29bf14b93d88fdbc4273ec,1786311146341103,438,2946,1,1786309659
28,a020a7482f29bf14b93d88fdbc4273ec,1786311038619103,228,2945,1,1786309659
29,a020a7482f29bf14b93d88fdbc4273ec,1786310866669811,263,2944,1,1786309659

In [100]:
con.execute("""
SELECT
    level_id,
    level_index,
    COUNT(*) AS rows
FROM '/content/level_start.parquet'
WHERE level_index > 500
GROUP BY level_id, level_index
ORDER BY rows DESC
LIMIT 50
""").df()

    level_id  level_index  rows
0        496          542    30
1        471          555    30
2        349          515    28
3        494          512    26
4        484          550    24
5        430          639    23
6        497          515    22
7        430          522    22
8        489          507    22
9        431          664    22
10       339          596    22
11       309          532    21
12       492          744    20
13       487          526    20
14       394          545    20
15       394          613    20
16       471          563    19
17       479          503    19
18       466          502    19
19       449          508    18
20       487          505    18
21       409          612    18
22       377          543    18
23       247          557    18
24       431          523    17
25       431          569    17
26       427          636    17
27       347          598    17
28       449          541    16
29       466          504    16
30       471          519    15
31       409         1132    15
32       471          537    15
33       394          823    15
34       409          501    15
35       464          503    14
36       436          552    14
37       284          639    14
38       471          510    14
39       449          657    14
40       411          593    14
41       409          634    14
42       394          663    14
43       309          628    14
44       259          596    14
45       397          640    14
46       475          514    13
47       484          502    13
48       467          559    13
49       434         1252    13

In [101]:
con.execute("""
SELECT
    level_id,
    COUNT(DISTINCT level_index) AS progression_positions,
    MIN(level_index) AS first_position,
    MAX(level_index) AS last_position,
    COUNT(*) AS starts,
    COUNT(DISTINCT user_pseudo_id) AS users
FROM '/content/level_start.parquet'
GROUP BY level_id
ORDER BY progression_positions DESC
LIMIT 30
""").df()

,level_id,progression_positions,first_position,last_position,starts,users
0,404,89,404,2763,967,292
1,408,86,408,2767,580,280
2,409,85,409,2923,1229,282
3,407,84,407,2766,446,273
4,424,83,424,2783,463,232
5,401,83,401,2760,335,297
6,402,82,402,2761,344,296
7,422,81,422,2781,388,238
8,410,80,410,2769,524,267
9,403,79,403,2762,478,295
10,423,79,423,2782,462,237
11,434,79,434,2793,1200,207
12,414,79,414,2773,523,252
13,418,79,418,2956,409,246
14,406,78,406,2765,386,279
15,438,78,438,2946,305,191
16,446,78,446,2805,470,179
17,415,78,415,2774,309,243
18,429,78,429,2788,789,222
19,464,77,464,2823,584,157
20,426,77,426,2785,411,228
21,421,77,421,2780,328,237
22,419,77,419,2907,1086,246
23,428,77,428,2787,409,222
24,431,76,431,2790,687,209
25,413,75,413,2772,343,254
26,412,75,412,2960,337,257
27,437,75,437,2796,482,191
28,432,75,432,2791,316,209
29,449,75,449,2808,775,176

In [102]:
con.execute("""
SELECT
    COUNT(*) AS rows,
    SUM(CASE WHEN level_id = level_index THEN 1 ELSE 0 END) AS same_id_index,
    ROUND(
        100.0 * SUM(CASE WHEN level_id = level_index THEN 1 ELSE 0 END)
        / COUNT(*),
        2
    ) AS same_pct
FROM '/content/level_start.parquet'
WHERE level_index <= 500
""").df()

      rows  same_id_index  same_pct
0  1259485      1255028.0     99.65

## 4. Level Difficulty Analysis

Level difficulty is evaluated across the first 500 progression levels.

`level_index` is used to define progression scope, while `level_id`
identifies the level content being evaluated.

Multiple gameplay metrics are used to capture different dimensions of
difficulty, including first-attempt win rate, overall attempt win rate,
average attempts, playtime, and revive usage.

In [103]:
level_metrics = con.execute("""
SELECT
    level_id,

    COUNT(*) AS attempts,

    COUNT(DISTINCT user_pseudo_id) AS users,

    ROUND(
        AVG(CASE WHEN status = 1 THEN 1.0 ELSE 0 END),
        4
    ) AS attempt_win_rate,

    ROUND(
        AVG(
            CASE
                WHEN attempt = 1
                THEN CASE WHEN status = 1 THEN 1.0 ELSE 0 END
            END
        ),
        4
    ) AS first_attempt_win_rate,

    ROUND(AVG(attempt), 2) AS avg_attempt,

    MEDIAN(attempt) AS median_attempt,

    ROUND(AVG(playtime), 2) AS avg_playtime,

    ROUND(
        AVG(CASE WHEN revive > 0 THEN 1.0 ELSE 0 END),
        4
    ) AS revive_rate,

    ROUND(AVG(unsolved_items), 2) AS avg_unsolved_items,

    ROUND(AVG(move), 2) AS avg_move

FROM '/content/level_end.parquet'

WHERE level_index BETWEEN 1 AND 500

GROUP BY level_id
ORDER BY level_id
""").df()

level_metrics.head()

,level_id,attempts,users,attempt_win_rate,first_attempt_win_rate,avg_attempt,median_attempt,avg_playtime,revive_rate,avg_unsolved_items,avg_move
0,1,12194,12029,0.9985,0.9985,1.00,1.0,9.53,0.0,0.00,1.09
1,2,12327,11964,0.9822,0.9915,1.00,1.0,10.09,0.0,0.01,2.05
2,3,12330,11872,0.9719,0.9784,1.02,1.0,13.49,0.0,0.06,3.33
3,4,11942,11777,0.9965,0.9970,1.01,1.0,17.50,0.0,0.01,6.32
4,5,11771,11611,0.9971,0.9977,1.01,1.0,39.65,0.0,0.01,13.52

In [104]:
level_metrics[
    level_metrics["users"] >= 100
].sort_values(
    "first_attempt_win_rate"
).head(20)

,level_id,attempts,users,attempt_win_rate,first_attempt_win_rate,avg_attempt,median_attempt,avg_playtime,revive_rate,avg_unsolved_items,avg_move
308,309,2436,496,0.1958,0.1463,5.39,4.0,120.28,0.5452,8.67,24.64
433,434,799,181,0.2140,0.2109,5.65,4.0,150.85,0.5181,9.82,24.96
303,304,2364,513,0.2077,0.2146,5.52,4.0,67.65,0.4150,7.68,14.20
393,394,1038,246,0.2283,0.2335,4.55,3.0,81.45,0.5058,6.70,18.74
448,449,463,148,0.3089,0.2538,3.42,3.0,172.23,0.5572,8.30,32.81
342,343,1054,366,0.3435,0.2741,3.03,2.0,189.21,0.4279,7.84,31.25
371,372,733,285,0.3888,0.2797,2.83,2.0,131.00,0.3806,6.77,26.55
429,430,895,191,0.2000,0.2865,5.83,4.0,100.38,0.5039,8.00,22.15
230,231,3482,917,0.2519,0.3104,6.85,3.0,111.64,0.3644,8.09,20.53
330,331,1127,403,0.3478,0.3120,3.17,2.0,157.17,0.4632,6.82,26.85
253,254,2532,711,0.2737,0.3137,5.17,3.0,103.43,0.4368,6.75,21.14
428,429,563,192,0.3410,0.3152,3.20,2.0,115.10,0.5506,6.87,28.49
465,466,367,123,0.3351,0.3214,3.52,2.0,80.32,0.4714,6.66,22.22
418,419,761,213,0.2707,0.3300,4.16,3.0,125.17,0.6124,7.26,25.22
348,349,986,333,0.3357,0.3400,3.84,2.0,102.47,0.4645,7.40,26.08
470,471,422,110,0.2559,0.3438,4.70,3.0,153.59,0.4953,7.84,24.31
233,234,2643,874,0.3250,0.3461,3.84,3.0,167.34,0.4211,7.32,29.04
379,380,789,271,0.3384,0.3502,3.57,2.0,82.36,0.3942,6.56,20.61
153,154,4899,1907,0.3815,0.3672,3.06,2.0,104.76,0.3484,6.75,26.69
188,189,4420,1315,0.2919,0.3814,5.80,3.0,113.81,0.3810,6.86,24.97

In [105]:
level_metrics[
    level_metrics["users"] >= 100
].sort_values(
    "avg_attempt",
    ascending=False
).head(20)

,level_id,attempts,users,attempt_win_rate,first_attempt_win_rate,avg_attempt,median_attempt,avg_playtime,revive_rate,avg_unsolved_items,avg_move
230,231,3482,917,0.2519,0.3104,6.85,3.0,111.64,0.3644,8.09,20.53
246,247,2837,769,0.2647,0.4031,6.13,4.0,120.57,0.4188,7.50,26.07
222,223,2962,959,0.3190,0.4443,5.98,3.0,140.87,0.3916,6.59,28.80
429,430,895,191,0.2000,0.2865,5.83,4.0,100.38,0.5039,8.00,22.15
188,189,4420,1315,0.2919,0.3814,5.80,3.0,113.81,0.3810,6.86,24.97
433,434,799,181,0.2140,0.2109,5.65,4.0,150.85,0.5181,9.82,24.96
303,304,2364,513,0.2077,0.2146,5.52,4.0,67.65,0.4150,7.68,14.20
308,309,2436,496,0.1958,0.1463,5.39,4.0,120.28,0.5452,8.67,24.64
253,254,2532,711,0.2737,0.3137,5.17,3.0,103.43,0.4368,6.75,21.14
466,467,369,118,0.3008,0.4190,4.92,3.0,117.21,0.3902,7.05,23.88
408,409,876,250,0.2774,0.4286,4.89,3.0,129.66,0.5080,7.65,25.40
196,197,3350,1212,0.3513,0.5085,4.70,3.0,114.33,0.3758,5.68,24.42
470,471,422,110,0.2559,0.3438,4.70,3.0,153.59,0.4953,7.84,24.31
333,334,1306,391,0.2963,0.4218,4.59,3.0,96.64,0.5008,6.42,22.32
393,394,1038,246,0.2283,0.2335,4.55,3.0,81.45,0.5058,6.70,18.74
228,229,2184,914,0.4176,0.5753,4.22,2.0,137.04,0.4492,4.81,29.32
418,419,761,213,0.2707,0.3300,4.16,3.0,125.17,0.6124,7.26,25.22
143,144,5643,2079,0.3604,0.4809,4.14,2.0,156.13,0.3911,7.33,30.65
186,187,2957,1334,0.4515,0.5485,4.09,2.0,114.53,0.4210,4.99,28.57
193,194,3604,1252,0.3410,0.4335,3.93,3.0,84.64,0.3421,4.20,18.04

## 5. Retry Behavior

To understand whether difficult levels immediately discourage players,
I analyze player behavior after a non-win outcome.

The key metric is `retry_after_fail_rate`, which measures the share of
failed attempts followed by another attempt on the same progression level.

In [106]:
journey_metrics = con.execute("""
WITH events AS (
    SELECT
        user_pseudo_id,
        end_ts,
        TRY_CAST(level_index AS INTEGER) AS level_index,
        TRY_CAST(level_id AS INTEGER) AS level_id,
        status
    FROM '/content/level_end.parquet'
    WHERE TRY_CAST(level_index AS INTEGER) BETWEEN 1 AND 500
),

sequenced AS (
    SELECT
        *,
        LEAD(level_index) OVER (
            PARTITION BY user_pseudo_id
            ORDER BY end_ts
        ) AS next_level_index
    FROM events
),

level_retry AS (
    SELECT
        level_id,

        COUNT(*) FILTER (
            WHERE status != 1
        ) AS failed_attempts,

        COUNT(*) FILTER (
            WHERE status != 1
              AND next_level_index = level_index
        ) AS retries_after_fail

    FROM sequenced
    GROUP BY level_id
)

SELECT
    level_id,
    failed_attempts,
    retries_after_fail,

    ROUND(
        retries_after_fail * 1.0
        / NULLIF(failed_attempts, 0),
        4
    ) AS retry_after_fail_rate

FROM level_retry
ORDER BY level_id
""").df()

journey_metrics.head()

   level_id  failed_attempts  retries_after_fail  retry_after_fail_rate
0         1               18                   6                 0.3333
1         2              220                 207                 0.9409
2         3              346                 309                 0.8931
3         4               42                  36                 0.8571
4         5               34                  30                 0.8824

In [107]:
level_analysis = level_metrics.merge(
    journey_metrics,
    on="level_id",
    how="left"
)

level_analysis.head(20)

,level_id,attempts,users,attempt_win_rate,first_attempt_win_rate,avg_attempt,median_attempt,avg_playtime,revive_rate,avg_unsolved_items,avg_move,failed_attempts,retries_after_fail,retry_after_fail_rate
0,1,12194,12029,0.9985,0.9985,1.00,1.0,9.53,0.0000,0.00,1.09,18,6,0.3333
1,2,12327,11964,0.9822,0.9915,1.00,1.0,10.09,0.0000,0.01,2.05,220,207,0.9409
2,3,12330,11872,0.9719,0.9784,1.02,1.0,13.49,0.0000,0.06,3.33,346,309,0.8931
3,4,11942,11777,0.9965,0.9970,1.01,1.0,17.50,0.0000,0.01,6.32,42,36,0.8571
4,5,11771,11611,0.9971,0.9977,1.01,1.0,39.65,0.0000,0.01,13.52,34,30,0.8824
5,6,11591,11432,0.9972,0.9975,1.02,1.0,41.55,0.0000,0.01,13.77,33,29,0.8788
6,7,11390,11228,0.9975,0.9979,1.02,1.0,62.87,0.0000,0.01,19.46,28,26,0.9286
7,8,11172,10991,0.9961,0.9971,1.03,1.0,45.67,0.0006,0.02,14.36,44,42,0.9545
8,9,11056,10697,0.9787,0.9797,1.05,1.0,54.75,0.0092,0.12,16.43,235,219,0.9319
9,10,10716,10476,0.9888,0.9931,1.05,1.0,67.60,0.0004,0.08,21.27,120,110,0.9167
10,11,10363,10205,0.9965,0.9973,1.03,1.0,68.43,0.0000,0.02,21.60,36,31,0.8611
11,12,10109,9962,0.9982,0.9988,1.04,1.0,85.96,0.0000,0.01,24.52,18,11,0.6111
12,13,9880,9708,0.9960,0.9962,1.04,1.0,72.99,0.0001,0.03,24.12,40,36,0.9000
13,14,9828,9548,0.9843,0.9850,1.04,1.0,91.62,0.0122,0.12,27.52,154,146,0.9481
14,15,9557,9402,0.9987,0.9987,1.01,1.0,68.51,0.0004,0.01,20.65,12,12,1.0000
15,16,9831,9205,0.9451,0.9515,1.09,1.0,77.67,0.0366,0.42,25.15,540,505,0.9352
16,17,9153,9011,0.9977,0.9982,1.02,1.0,72.25,0.0010,0.02,25.29,21,21,1.0000
17,18,9088,8907,0.9928,0.9953,1.03,1.0,79.20,0.0042,2.07,26.32,65,60,0.9231
18,19,9078,8809,0.9826,0.9831,1.03,1.0,72.31,0.0165,0.16,31.82,158,151,0.9557
19,20,8828,8701,0.9991,0.9993,1.01,1.0,35.54,0.0000,0.01,10.38,8,8,1.0000

## 6. Progression Drop-off Analysis

To measure progression friction, I calculate the share of players who reached
a progression level but did not appear at the next progression level.

The analysis is limited to progression positions 1–500 to keep the scope
consistent with the difficulty analysis.

In [108]:
progression_drop_all = con.execute("""
WITH reached AS (
    SELECT DISTINCT
        user_pseudo_id,
        TRY_CAST(level_index AS INTEGER) AS level_index
    FROM '/content/level_start.parquet'
    WHERE TRY_CAST(level_index AS INTEGER) BETWEEN 1 AND 500
),

level_reach AS (
    SELECT
        level_index,
        COUNT(DISTINCT user_pseudo_id) AS users_reached
    FROM reached
    GROUP BY level_index
),

next_reach AS (
    SELECT
        level_index - 1 AS level_index,
        COUNT(DISTINCT user_pseudo_id) AS users_reached_next
    FROM reached
    GROUP BY level_index
)

SELECT
    l.level_index,
    l.users_reached,
    COALESCE(n.users_reached_next, 0) AS users_reached_next,

    ROUND(
        1.0 - COALESCE(n.users_reached_next, 0) * 1.0 / l.users_reached,
        4
    ) AS dropoff_rate

FROM level_reach l

LEFT JOIN next_reach n
    USING(level_index)

WHERE l.users_reached >= 100

ORDER BY l.level_index
""").df()

progression_drop_all.head(10)

   level_index  users_reached  users_reached_next  dropoff_rate
0            1          11775               12020       -0.0208
1            2          12020               11928        0.0077
2            3          11928               11828        0.0084
3            4          11828               11745        0.0070
4            5          11745               11562        0.0156
5            6          11562               11406        0.0135
6            7          11406               11255        0.0132
7            8          11255               10965        0.0258
8            9          10965               10666        0.0273
9           10          10666               10448        0.0204

In [109]:
progression_drop_all.sort_values(
    "dropoff_rate",
    ascending=False
).head(20)

     level_index  users_reached  users_reached_next  dropoff_rate
408          409            219                 205        0.0639
433          434            173                 162        0.0636
303          304            515                 484        0.0602
466          467            135                 127        0.0593
471          472            120                 113        0.0583
230          231            926                 872        0.0583
143          144           2117                2005        0.0529
308          309            503                 477        0.0517
429          430            183                 174        0.0492
393          394            248                 236        0.0484
153          154           1937                1844        0.0480
246          247            780                 743        0.0474
253          254            721                 688        0.0458
106          107           2759                2633        0.0457
188          189           1334                1273        0.0457
28            29           7521                7188        0.0443
196          197           1219                1165        0.0443
263          264            668                 639        0.0434
193          194           1264                1210        0.0427
39            40           5755                5512        0.0422

### Map Progression Position to Level Content

`level_index` represents the player's progression position, while `level_id`
identifies the level content.

For each progression position, the most frequently observed `level_id`
is used as the representative content mapping.

In [110]:
level_mapping = con.execute("""
WITH mapping AS (
    SELECT
        TRY_CAST(level_index AS INTEGER) AS level_index,
        TRY_CAST(level_id AS INTEGER) AS level_id,
        COUNT(*) AS n,

        ROW_NUMBER() OVER (
            PARTITION BY TRY_CAST(level_index AS INTEGER)
            ORDER BY COUNT(*) DESC
        ) AS rn

    FROM '/content/level_start.parquet'

    WHERE TRY_CAST(level_index AS INTEGER) BETWEEN 1 AND 500

    GROUP BY
        TRY_CAST(level_index AS INTEGER),
        TRY_CAST(level_id AS INTEGER)
)

SELECT
    level_index,
    level_id

FROM mapping

WHERE rn = 1

ORDER BY level_index
""").df()

level_mapping.head(10)

   level_index  level_id
0            1         1
1            2         2
2            3         3
3            4         4
4            5         5
5            6         6
6            7         7
7            8         8
8            9         9
9           10        10

### Priority Scoring

To support level prioritization, I created a heuristic score combining:

- 40% difficulty
- 40% progression drop-off
- 20% player exposure

This score is used only as a prioritization aid, not as a causal or predictive model.

In [111]:
drop_with_content = progression_drop_all.merge(
    level_mapping,
    on="level_index",
    how="left"
)

drop_with_content.head()

   level_index  users_reached  users_reached_next  dropoff_rate  level_id
0            1          11775               12020       -0.0208         1
1            2          12020               11928        0.0077         2
2            3          11928               11828        0.0084         3
3            4          11828               11745        0.0070         4
4            5          11745               11562        0.0156         5

In [112]:
priority_levels = drop_with_content.merge(
    level_analysis,
    on="level_id",
    how="left"
)

priority_levels[
    [
        "level_id",
        "users_reached",
        "dropoff_rate",
        "first_attempt_win_rate",
        "avg_attempt",
        "revive_rate",
        "retry_after_fail_rate"
    ]
].sort_values(
    ["dropoff_rate", "first_attempt_win_rate"],
    ascending=[False, True]
).head(20)

,level_id,users_reached,dropoff_rate,first_attempt_win_rate,avg_attempt,revive_rate,retry_after_fail_rate
408,409,219,0.0639,0.4286,4.89,0.5080,0.9874
433,434,173,0.0636,0.2109,5.65,0.5181,0.9809
303,304,515,0.0602,0.2146,5.52,0.4150,0.9861
466,467,135,0.0593,0.4190,4.92,0.3902,0.9729
230,231,926,0.0583,0.3104,6.85,0.3644,0.9804
471,472,120,0.0583,0.5000,1.92,0.4607,0.9885
143,144,2117,0.0529,0.4809,4.14,0.3911,0.9800
308,309,503,0.0517,0.1463,5.39,0.5452,0.9898
429,430,183,0.0492,0.2865,5.83,0.5039,0.9832
393,394,248,0.0484,0.2335,4.55,0.5058,0.9888
153,154,1937,0.0480,0.3672,3.06,0.3484,0.9766
246,247,780,0.0474,0.4031,6.13,0.4188,0.9875
253,254,721,0.0458,0.3137,5.17,0.4368,0.9880
188,189,1334,0.0457,0.3814,5.80,0.3810,0.9863
106,107,2759,0.0457,0.4739,2.99,0.2883,0.9798
196,197,1219,0.0443,0.5085,4.70,0.3758,0.9770
28,29,7521,0.0443,0.7311,1.55,0.2168,0.9566
263,264,668,0.0434,0.3940,3.65,0.4305,0.9838
193,194,1264,0.0427,0.4335,3.93,0.3421,0.9815
39,40,5755,0.0422,0.7430,1.60,0.2252,0.9636

In [113]:
rank_df = priority_levels.copy()

rank_df["difficulty_score"] = 1 - rank_df["first_attempt_win_rate"]
rank_df["exposure_score"] = rank_df["users_reached"] / rank_df["users_reached"].max()

rank_df["priority_score"] = (
    0.4 * rank_df["difficulty_score"] +
    0.4 * rank_df["dropoff_rate"] / rank_df["dropoff_rate"].max() +
    0.2 * rank_df["exposure_score"]
)

rank_df[
    [
        "level_id",
        "users_reached",
        "first_attempt_win_rate",
        "avg_attempt",
        "dropoff_rate",
        "priority_score"
    ]
].sort_values(
    "priority_score",
    ascending=False
).head(10)

,level_id,users_reached,first_attempt_win_rate,avg_attempt,dropoff_rate,priority_score
433,434,173,0.2109,5.65,0.0636,0.716641
303,304,515,0.2146,5.52,0.0602,0.699568
308,309,503,0.1463,5.39,0.0517,0.673480
230,231,926,0.3104,6.85,0.0583,0.656193
408,409,219,0.4286,4.89,0.0639,0.632204
393,394,248,0.2335,4.55,0.0484,0.613700
466,467,135,0.4190,4.92,0.0593,0.605851
429,430,183,0.2865,5.83,0.0492,0.596426
153,154,1937,0.3672,3.06,0.0480,0.585819
143,144,2117,0.4809,4.14,0.0529,0.574007

In [114]:
final_shortlist = level_analysis[
    level_analysis["level_id"].isin([434, 304, 231, 309])
][
    [
        "level_id",
        "users",
        "first_attempt_win_rate",
        "attempt_win_rate",
        "avg_attempt",
        "avg_playtime",
        "revive_rate",
        "retry_after_fail_rate"
    ]
].copy()

final_shortlist

,level_id,users,first_attempt_win_rate,attempt_win_rate,avg_attempt,avg_playtime,revive_rate,retry_after_fail_rate
230,231,917,0.3104,0.2519,6.85,111.64,0.3644,0.9804
303,304,513,0.2146,0.2077,5.52,67.65,0.4150,0.9861
308,309,496,0.1463,0.1958,5.39,120.28,0.5452,0.9898
433,434,181,0.2109,0.2140,5.65,150.85,0.5181,0.9809

In [115]:
dashboard_levels = level_analysis.merge(
    drop_with_content[
        ["level_id", "users_reached", "users_reached_next", "dropoff_rate"]
    ],
    on="level_id",
    how="left"
)

dashboard_levels["is_priority"] = dashboard_levels["level_id"].isin(
    [231, 304, 309, 434]
)

dashboard_levels.to_csv(
    "/content/drive/MyDrive/Project/DA_GAME/dashboard_levels.csv",
    index=False
)

dashboard_levels.head()

,level_id,attempts,users,attempt_win_rate,first_attempt_win_rate,avg_attempt,median_attempt,avg_playtime,revive_rate,avg_unsolved_items,avg_move,failed_attempts,retries_after_fail,retry_after_fail_rate,users_reached,users_reached_next,dropoff_rate,is_priority
0,1,12194,12029,0.9985,0.9985,1.00,1.0,9.53,0.0,0.00,1.09,18,6,0.3333,11775.0,12020.0,-0.0208,False
1,2,12327,11964,0.9822,0.9915,1.00,1.0,10.09,0.0,0.01,2.05,220,207,0.9409,12020.0,11928.0,0.0077,False
2,3,12330,11872,0.9719,0.9784,1.02,1.0,13.49,0.0,0.06,3.33,346,309,0.8931,11928.0,11828.0,0.0084,False
3,4,11942,11777,0.9965,0.9970,1.01,1.0,17.50,0.0,0.01,6.32,42,36,0.8571,11828.0,11745.0,0.0070,False
4,5,11771,11611,0.9971,0.9977,1.01,1.0,39.65,0.0,0.01,13.52,34,30,0.8824,11745.0,11562.0,0.0156,False